### PR TITLE
Fix daemon host/port setting to allow tab switching

### LINKED ISSUE #1688: Tabbing between fields in GUI wallet doesn't work -- inserts literal tab
OS: Linux
Wallet version: v0.13.0.3 (Qt 5.7.0)

tabbing-2018-10-21_04 28 22

Expected behavior: switch to next field, like on a website.

I'm assuming this is unintended since URLs/Ports shouldn't have tabs in them.

I realize this is low priority, and I'm happy to fix if y'all would like

Note that tabbing seems to work properly for username/password for connecting to a remote node.

### PR DESCRIPTION
**Pull request by sectioneight**
Previously, these were multiline editing (for some reason I'm not sure,
perhaps you can have multiple remote nodes?)

I tried various workarounds, but the simplest was to change them to
simply LineEdit (like username/password) and now my bug is fixed.

Fixes #1688

NOTE: Github isn't letting me update my PR or comment on this one, should I close and re-open?

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Could you PR this against the `release-v0.13` branch too?

**Comment by MaxXor** [comment]
There is something wrong with the commits in here. Please fix that before it can get merged.

**Comment by dEBRUYNE-1** [comment]
@sectioneight - What I meant was open a duplicate PR against the `release-v0.13` branch. Also, this PR was rebased erroneously (as it includes a lot of irrelevant commits).

**Comment by sectioneight** [comment]
Sorry, was having some GitHub issues yesterday. Fixing now.

**Comment by sectioneight** [comment]
Sorry about that, was having some GitHub issues yesterday. Closing and re-opening a new PR.

**Comment by sectioneight** [comment]
New PR: #1693

**Pull request closed without merging**
