### PR TITLE
main: hide Unlock time when switching wallets

### LINKED ISSUE #1403: Unlock time is Visible when switch to wallet
Windows x64 GUI Wallet 0.12.0

When staying in-app and you close one wallet and open another, if that wallet has recently received a transaction, it will show the balance unlock time prior wallet unlock to successful wallet password.

monero wallet balance unlock time visible circled

Does not appear to be a serious issue, however could raise concerns regarding privacy.

### PR DESCRIPTION
**Pull request by mmbyday**
resolves #1403

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Does this resolve #1159 too?

**Comment by mmbyday** [comment]
No. Whatever page, such as the setting page, was open previously, is still showing in the background. What kind of behavior would you prefer to happen in #1159?

**Comment by xmrdsc** [comment]
Nice!

**Comment by dEBRUYNE-1** [comment]
@mmbyday - Perhaps simply the wizard page where the user can select the different options (create a new wallet, restore from the 25 word mnemonic seed etc.)?

**Comment by mmbyday** [comment]
@dEBRUYNE-1 Terrific idea. Implemented by #1837 :)

**Comment by dEBRUYNE-1** [comment]
@mmbyday - Nice one :+1:

**Pull request merged**
