### PR TITLE
PasswordDialog: hide balance when passwordDialog is open :sparkles:

### PR DESCRIPTION
**Pull request by mmbyday**
Before
bef

After
aft134

### CODE REVIEW

**Comment by mmbyday** [comment]
Collaborates well with #1814

**Comment by xiphon** [comment]
Would be better to avoid changing persistent settings

```diff
diff --git a/components/PasswordDialog.qml b/components/PasswordDialog.qml
index d0f442e..e79b6a3 100644
--- a/components/PasswordDialog.qml
+++ b/components/PasswordDialog.qml
@@ -61,6 +61,8 @@ Item {
         root.visible = true;
         passwordInput.forceActiveFocus();
         passwordInput.text = ""
+        appwindow.hideBalanceForced = true;
+        appwindow.updateBalance();
     }
 
     function showError(errorText) {
@@ -73,6 +75,8 @@ Item {
         middlePanel.enabled = true
         titleBar.enabled = true
         root.visible = false;
+        appwindow.hideBalanceForced = false;
+        appwindow.updateBalance();
         closeCallback();
     }
 
diff --git a/main.qml b/main.qml
index 168473f..b59326a 100644
--- a/main.qml
+++ b/main.qml
@@ -48,6 +48,7 @@ ApplicationWindow {
     title: "Monero"
 
     property var currentItem
+    property bool hideBalanceForced: false
     property bool whatIsEnable: false
     property bool ctrlPressed: false
     property bool rightPanelExpanded: false
@@ -353,12 +354,9 @@ ApplicationWindow {
     }
 
     function updateBalance() {
-        if (!currentWallet)
-            return;
-
         var balance_unlocked = qsTr("HIDDEN");
         var balance = qsTr("HIDDEN");
-        if(!persistentSettings.hideBalance){
+        if(!hideBalanceForced && !persistentSettings.hideBalance && currentWallet){
             balance_unlocked = walletManager.displayAmount(currentWallet.unlockedBalance(currentWallet.currentSubaddressAccount));
             balance = walletManager.displayAmount(currentWallet.balance(currentWallet.currentSubaddressAccount));
         }
```

**Comment by mmbyday** [comment]
Sure, sounds reasonable. Shall I close this PR and you open a new one with your patch?

**Comment by xiphon** [comment]
#1829

**Pull request closed without merging**
