### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by leonklingele**
Reviving #1026. Work done by @Schnoffel with a few fixes from myself as noted by @erciccione.

### CODE REVIEW

**Comment by Schnoffel** [comment]
Thank you @leonklingele.

**Comment by leonklingele** [comment]
Well, it's your work. Thank __you__ :-)

**Comment by Schnoffel** [comment]
As on Windows I only have problems to get git running I moved to my Linux server now which I am much more familiar with. When I do new translations should I fork your fork (so the translations from November 2017 are not lost) and make a new PR or what would the best approach? : )

Thanks also for your step-by-step instruction in the other PR but I could not try it as I could not get it running on Windows.

**Comment by leonklingele** [comment]
Once this PR with your translations gets merged (into the `master` branch of the `monero-gui` repo), simply update your copy ("Git clone") as follows:

```sh
$ git remote add upstream https://github.com/monero-project/monero-gui.git
$ git fetch upstream
$ git checkout master # Checkout your master branch
$ git pull upstream master # .. and pull in the changes which will also includes this PR
```

Make sure to not do any further work in your `master` branch, instead commit your changes into a custom branch. This makes a lot of things easier for you. To create a new branch based on `master`, run `git checkout -b your-new-branch master`.

Also check out this interactive Git tutorial: https://learngitbranching.js.org/ :)

**Comment by Schnoffel** [comment]
Okay, thank you! : )

**Pull request merged**
