### PR TITLE
Some polish translations

### PR DESCRIPTION
**Pull request by szogun1987**
I haven't built project after my changes, so I haven't checked if it runs properly (and if translations matches sizes of UI).
Please don't merge this PR immediately, I would share it in PR and ask for comments.

### CODE REVIEW

**Comment by erciccione** [comment]
Hi @szogun1987 thank you for this updates, but looks like you a conflict, can you fix it and then squash your commits?

**Comment by szogun1987** [comment]
OK. I will try (yesterday I tried to apply reverse PR and it sid that there is nothing to merge).

**Comment by erciccione** [comment]
You don't need to reverse the PR but just pull the updated monero-core_pl.ts file (it probably changed after #1076 ) and fix the conflicts, you'll find some more strings. if you need live support come chat on `#monero-translations` :)

**Comment by szogun1987** [comment]
I will not actively update translations. I will review this file from time to time.

**Comment by szogun1987** [comment]
I have one question: How to make squash commit without using push --force? Is there some option in GitHub itself.

**Comment by erciccione** [comment]
>I will not actively update translations. I will review this file from time to time.

yes sure, no problem

>I have one question: How to make squash commit without using push --force? Is there some option in GitHub itself.

AFAIK no, after squashing you change the story of the repo , you need to force the push or git will not accept the changes. Also afaik, GitHub can't squash

**Comment by szogun1987** [comment]
OK. I will do it tomorrow.

**Comment by erciccione** [comment]
@szogun1987 any update on this?

**Comment by szogun1987** [comment]
Sorry, I had lot of work in my day to day job. I will update this PR soon.

**Comment by einsteinsfool** [comment]
I took the file from your PR, removed the comments and filled the gaps.
I can send you the file, make another PR or maybe somehow suggest changes to this PR (never did the latter before).
What do you prefer?

**Comment by szogun1987** [comment]
List of all mine comments from translations file:


If tx is not abbrev from transaction, all translations that contains it should be updated


``` 
<location filename="../components/HistoryTable.qml" line="52"/>
<source>Destinations:</source>
```
If it is transaction receivers adresses Odbiorcy is valid, otherwise Cele:


```
<location filename="../LeftPanel.qml" line="108"/>
<source>Testnet</source>
```
Monero users knows what Testnet means and there is no good, short, polish word for it

```
<location filename="../LeftPanel.qml" line="320"/>
<source>Address book</source>
```
Odbiorcy (Receivers) seems to be better in this context 


```
<location filename="../LeftPanel.qml" line="415"/>
<source>Mining</source>
```
It may be untranslated also

```
<location filename="../pages/Mining.qml" line="83"/>
<source>Mining with your computer helps strengthen the Monero network. The more that people mine, the harder it is for the network to be attacked, and every little bit helps.&lt;br&gt; &lt;br&gt;Mining also gives you a small chance to earn some Monero. Your computer will create hashes looking for block solutions. If you find a block, you will get the associated reward. Good luck!</source>
```
In my opinion this text should start with:
"Mining gives you a chance to earn extra Monero, in exchange to you computer power." 
It shows what user can gain with mining 


```
<location filename="../pages/Settings.qml" line="563"/>
<source>Rescan wallet cache</source>
```
There is no good translation for cache. So I used dane (data).


 Daemon has no good translation in Polish. Closest one is usługa (eng. Service)

 ```
 <location filename="../main.qml" line="1613"/>
 <source>Daemon will still be running in background when GUI is closed.</source>
  <translation type="unfinished">Usługa będzie dalej działała w tle po zamknięciu okna</translation>
```
From non-power-user point of view this translation is good enough

```
<location filename="../main.qml" line="819"/>
<source>This address received %1 monero, but the transaction is not yet mined</source>
```
In my opinion it should changed to:
This address received %1 monero, but the transaction is not yet confirmed.

```
<location filename="../main.qml" line="1317"/>
<source>send to the same destination</source>
<translation>wyślij do tego samego celu</translation>
```
I think: Wyślij do tego samego odbiorcy would be better

**Comment by szogun1987** [comment]
I have 2 options: discuss those changes in this PR or copy mine comment above to new issue and discuss it in there.

**Comment by einsteinsfool** [comment]
Tx is the abbreviation for transaction so everything's fine.

I translated `Destinations:` to `Adresy docelowe:`. A bit more precise than `Cele:`. So it's a compromise between the 2 options you proposed.

`Testnet` I translated to `Sieć testowa`. I think it's the same in English and in Polish. Users will just have to learn what "Testnet" and "Sieć testowa" are.

`Address book` feels more like `Książka adresowa` than `Odbiorcy` imo because it suggests that there's a list of some sort.

I translated `Mining` to `Kopanie`. I think it's a widely used term in Polish. We even have "koparka" which is a miner. People would understand that imo.

I translated "cache" to "pamięć podręczna" but your translation seems better so I updated it.

I think translating daemon to demon is a good idea, although it's hard to understand. It's more precise than service and Monero users will have to learn some language anyway. Like ringsize, blockchain, seed, etc. We can just translate to Polish this guide and it should help Polish users:
https://medium.com/@Electricsheep56/the-monero-gui-wallet-broken-down-in-plain-english-bd2889b8c202

As for your other suggestions to change existing phrases, I agree with most of them but for now we should focus on just translating and present your mentioned fixes in another PR.

**Comment by szogun1987** [comment]
Hi @einsteinsfool I have taken into account your comments.
@erciccione Can you check if current state satisfies you?

**Comment by erciccione** [comment]
Ok @szogun1987 you only need to make a commit who uncomment [this string](https://github.com/monero-project/monero-gui/blob/master/lang/languages.xml#L33), then would be perfect to squash your precedent commits if @einsteinsfool is done reviewing

**Comment by szogun1987** [comment]
OK Done.

**Comment by erciccione** [comment]
i'm reviewing the PR but i found that you left `type="unfinished"` in many strings. you need to remove that or the source string will be used.
The correct format of a ready string should be
```
<source>Invalid address</source>
<translation>Niepoprawny adres</translation>
```

**Comment by szogun1987** [comment]
In most cases I left it if I weren't sure if mine translation should be used (I have also removed this attribute from couple translations).

**Comment by erciccione** [comment]
I understand, but at the moment most of the strings are marked `unfinished`, this means the Polish localization will contain mainly english text if this PR will be merged as it is and i don't see the point of it. If you are unsure your translation is correct, i'm sure @einsteinsfool will be happy to help, but please remove the `unfinished` attribute where not needed.

**Comment by szogun1987** [comment]
OK. I will review it soon. Why builds of this branch fail? I haven't changed anything that should affect build process.

**Comment by erciccione** [comment]
Don't worry this branch doesn't fail, there is just a problem with the win64 buildbot, all other bots built correctly

**Comment by einsteinsfool** [comment]
@szogun1987 Would you mind if I made another PR (filling untranslated phrases) including your changes from this PR? It would still make you a contributor and your changes would be used but it would be easier for me than to update this PR which I was unable to do. Believe me, I tried updating this PR for 2 hours but I'm a noob with git and couldn't do it.

**Comment by szogun1987** [comment]
@einsteinsfool  It would be OK for me.

**Comment by erciccione** [comment]
This PR can now be closed in favour of #1133

**Comment by jonathancross** [comment]
@szogun1987 Please review #1133 and close this when you have a chance.  Thanks!

**Comment by luigi1111** [comment]
Looks like Github says both PRs were merged, so I guess we're good here.

**Pull request merged**
