### PR TITLE
Settings overhaul

### PR DESCRIPTION
**Pull request by skftn**
Change of layout. Introduced sub-navigation. Context: #1361. 

Layout is responsive to account for different screen sizes and translation strings.

### CODE REVIEW

**Comment by luigi1111** [comment]
Shouldn't this be against master?

**Comment by skftn** [comment]
I made a mess here. Ill PR another.

**Comment by stoffu** [comment]
Maybe then remove the "Seed & Keys" button from the left panel?

**Comment by stoffu** [comment]
The "GUI version" and "Embedded Monero version" fields seem missing?

**Comment by stoffu** [comment]
When clicking on the `(change)` hyperlink next to the `Wallet creation height`, the wallet doesn't seem to start rescanning the blockchain. Currently, it pops up a confirmation dialog followed by blockchain rescanning.

**Comment by skftn** [comment]
> The Layout tab becomes blank when resized to the mobile mode

Fixed. I [now show a message](https://i.imgur.com/cysRDKU.png).

> Maybe then remove the "Seed & Keys" button from the left panel?

Keeping it in for now, trying to make the 0.12.4 release. Could definitely remove it later. 

> The "GUI version" and "Embedded Monero version" fields seem missing?

Fixed.

> When clicking on the (change) hyperlink next to the Wallet creation height, the wallet doesn't seem to start rescanning the blockchain.

My bad, this is fixed now.

In addition; I made the info section copyable to clipboard:



And the grey fonts are a tad bit lighter now

**Comment by skftn** [comment]
Moo mentioned to emphasize on the fact third-party remote nodes are less secure. Placed a warning box there.

**Comment by stoffu** [comment]
@skftn:
Looks good, just one issue: the log level in the "Log" tab doesn't seem responding to click.

**Comment by skftn** [comment]
Yeah, looks broken on my laptop:



Will fix later tonight.

**Comment by skftn** [comment]
Should be fixed now.

**Pull request merged**
