### PR TITLE
Fix double titlebar

### LINKED ISSUE #1531: Two TitleBars on Arch Linux with Gnome 3
titlebar

### PR DESCRIPTION
**Pull request by MaxXor**
Fixes #1531

### CODE REVIEW

**Comment by selsta** [comment]
Can someone review this on Windows?

**Comment by xmrdsc** [comment]
Works as expected on Windows.

**Comment by MaxXor** [comment]
This should get included in the next release imho, it's very unesthetic on latest systems.

**Comment by selsta** [comment]
It’s in the merge queue :)

**Pull request merged**
