### PR TITLE
Fixed russian translation

### PR DESCRIPTION
**Pull request by kerastinell**
I've corrected typos @LvMsterfild made in Russian translation (PR #1427)

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks. Could you squash those two commits in just one?

**Comment by LvMsterfild** [comment]
Everything is OK. Please update fixes

**Comment by kerastinell** [comment]
I hope I've done squashing properly :)

**Comment by erciccione** [comment]
actually, no:) i think some past commits got into your squash and that created conflicts. How did you squash? maybe we can follow back those steps and see what happened

**Comment by kerastinell** [comment]
Here's how I squashed commits, @erciccione 
```
git commit -m "Fixed russian translation for \"Embedded Monero vesrion\""
git rebase -i HEAD~2
git push origin master --force
```

**Comment by erciccione** [comment]
that looks good, don't know what went wrong, can you use the reflog to go back to the HEAD before the rebase and then try again?

**Comment by kerastinell** [comment]
That's very strange, reflog shows only 1 line:

`1b705bd (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: clone: from https://github.com/kerastinell/monero-gui`

Can you close this PR so I can create a good working one, please? I'm sorry for caused inconvenience.

**Comment by erciccione** [comment]
Strange indeed. You can close this PR by yourself and then push another one

**Pull request closed without merging**
