### PR TITLE
history: change sent transaction dot color from orange to red

### PR DESCRIPTION
**Pull request by rating89us**
Red is the most commonly used color for outgoing transactions in cryptocurrency wallets.
image

### CODE REVIEW

**Comment by xmrdsc** [comment]
I'm not sure if this is needed. @GBKS designed the color scheme.

**Comment by xiphon** [comment]
IMO red dots look somewhat inconsistent

**Comment by GBKS** [comment]
My issue with red is that in UI design it usually means that an error happened, which is not the case here. I'd suggest sticking with orange to indicate outgoing transactions.

**Comment by elibroftw** [comment]
This should be closed then

**Pull request closed without merging**
