### PR TITLE
Fix Arabic translation listed twice in the project file

### PR DESCRIPTION
**Pull request by glv2**

### CODE REVIEW

**Comment by glv2** [comment]
Note: this PR is unnecessary if #1017 get merged.

**Comment by luigi1111** [comment]
@glv2 would you mind rebasing? It looks like there's not agreement on #1017 yet, but this PR could be merged in the meantime.

**Comment by glv2** [comment]
@luigi1111 rebased on fdaf557b994cd206782a1e039c6455c8dcc850ab

**Comment by luigi1111** [comment]
@glv2 thanks!

**Pull request merged**
