### PR TITLE
Add zeroMQ to installation instructions

### PR DESCRIPTION
**Pull request by aekrylov**

### CODE REVIEW

**Comment by stoffu** [comment]
Maybe you could also update the sections for OSX and Windows?

**Comment by aekrylov** [comment]
Copypasted package list for msys, added zmq for OS X

**Comment by luigi1111** [comment]
Hey @aekrylov would you mind squashing these two commits (you also didn't sign the second one it looks like)? Thanks.

**Comment by aekrylov** [comment]
Okay, you made me set up commit signing :) squashed and signed now

**Pull request merged**
