### PR TITLE
cmake: implement MacOS 'release' build + CI support

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by selsta** [comment]
I have been getting the following for a while now:

```
AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/qt/MoneroSettings.h"
into
  "SRC:/build/release/src/monero-wallet-gui_autogen/WTNNEUUVOU/moc_MoneroSettings.cpp"

Command
-------
/Users/selsta/dev/Qt/5.15.0/clang_64/bin/moc -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_LOCALE_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DDEVICE_TREZOR_READY=1 -DDISABLE_PASS_STRENGTH_METER -DHAVE_TREZOR_LIBUSB=1 -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_WIDGETS_LIB -I/usr/local/Cellar/libusb/1.0.23/include/libusb-1.0 -I/usr/local/Cellar/qt/5.15.0/include -I/Users/qt/work/install/lib/QtQuick.framework/Headers -I/Users/qt/work/install/lib/QtSvg.framework/Headers -I/Users/qt/work/install/lib/QtWidgets.framework/Headers -I/Users/qt/work/install/lib/QtXml.framework/Headers -I/Users/qt/work/install/lib/QtMacExtras.framework/Headers -I/Users/qt/work/install/lib/QtGui.framework/Headers -I/Users/qt/work/install/lib/QtQmlModels.framework/Headers -I/Users/qt/work/install/lib/QtQml.framework/Headers -I/Users/qt/work/install/lib/QtXmlPatterns.framework/Headers -I/Users/qt/work/install/lib/QtNetwork.framework/Headers -I/Users/qt/work/install/lib/QtCore.framework/Headers -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtGui.framework/Versions/5/Headers/5.15.0 -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtGui.framework/Versions/5/Headers/5.15.0/QtGui -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtCore.framework/Versions/5/Headers/5.15.0 -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtCore.framework/Versions/5/Headers/5.15.0/QtCore -I/Users/selsta/dev/monero-gui/monero/include -I/Users/selsta/dev/monero-gui/monero/src -I/Users/selsta/dev/monero-gui/monero/external/easylogging++ -I/Users/selsta/dev/monero-gui/monero/contrib/epee/include -I/Users/selsta/dev/monero-gui/src -I/Users/selsta/dev/monero-gui/src/daemon -I/Users/selsta/dev/monero-gui/src/libwalletqt -I/Users/selsta/dev/monero-gui/src/model -I/Users/selsta/dev/monero-gui/src/QR-Code-generator -I/Users/selsta/dev/monero-gui/src/QR-Code-scanner -I/Users/selsta/dev/monero-gui/src/zxcvbn-c -I/usr/local/include/hidapi -I/usr/local/opt/openssl@1.1/include -I/usr/local/include -I/usr/include/malloc -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F /Users/qt/work/install/lib --include /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/moc_predefs.h -p qt --output-dep-file -o /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/WTNNEUUVOU/moc_MoneroSettings.cpp /Users/selsta/dev/monero-gui/src/qt/MoneroSettings.h

Output
------
/Users/selsta/dev/monero-gui/src/qt/MoneroSettings.h:51: Error: Undefined interface
```

**Comment by selsta** [comment]
And when manually replacing `MoneroSettings` with normal `Settings`:

```
[ 82%] Building CXX object src/CMakeFiles/monero-wallet-gui.dir/monero-wallet-gui_autogen/mocs_compilation.cpp.o
In file included from /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/mocs_compilation.cpp:2:
In file included from /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/EWIEGA46WW/moc_NetworkType.cpp:10:
/Users/selsta/dev/monero-gui/src/NetworkType.h:31:10: fatal error: 'QObject' file not found
#include <QObject>
         ^~~~~~~~~
[ 83%] Linking CXX executable ../../../bin/monero-gen-trusted-multisig
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
1 error generated.
make[3]: *** [src/CMakeFiles/monero-wallet-gui.dir/monero-wallet-gui_autogen/mocs_compilation.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/monero-wallet-gui.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 83%] Built target gen_multisig
^Cmake[3]: *** [monero/src/wallet/CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o] Interrupt: 2
make[2]: *** [monero/src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Interrupt: 2
make[3]: *** [monero/src/simplewallet/CMakeFiles/simplewallet.dir/simplewallet.cpp.o] Interrupt: 2
make[2]: *** [monero/src/simplewallet/CMakeFiles/simplewallet.dir/all] Interrupt: 2
make[1]: *** [all] Interrupt: 2
make: *** [release] Interrupt: 2
```

Seeing that CI compiles fine no idea what is happening here :/

**Comment by selsta** [comment]
Sorry for spam but third update: Using brew installed Qt results in being able to compile fine using cmake + this PR.

**Comment by selsta** [comment]
```
AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/qt/MoneroSettings.h"
into
  "SRC:/build/release/src/monero-wallet-gui_autogen/WTNNEUUVOU/moc_MoneroSettings.cpp"

Command
-------
/Users/selsta/dev/Qt/5.15.0/clang_64/bin/moc -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_LOCALE_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DDISABLE_PASS_STRENGTH_METER -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QML_LIB -DQT_WIDGETS_LIB -I/usr/local/Cellar/qt/5.15.0/include -I/usr/local/Cellar/qt/5.15.0/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtSvg.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtXml.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtMacExtras.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtQmlModels.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtXmlPatterns.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtGui.framework/Versions/5/Headers/5.15.0 -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtGui.framework/Versions/5/Headers/5.15.0/QtGui -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtCore.framework/Versions/5/Headers/5.15.0 -I/Users/selsta/dev/Qt/5.15.0/clang_64/lib/QtCore.framework/Versions/5/Headers/5.15.0/QtCore -I/Users/selsta/dev/monero-gui/monero/include -I/Users/selsta/dev/monero-gui/monero/src -I/Users/selsta/dev/monero-gui/monero/external/easylogging++ -I/Users/selsta/dev/monero-gui/monero/contrib/epee/include -I/Users/selsta/dev/monero-gui/src -I/Users/selsta/dev/monero-gui/src/daemon -I/Users/selsta/dev/monero-gui/src/libwalletqt -I/Users/selsta/dev/monero-gui/src/model -I/Users/selsta/dev/monero-gui/src/QR-Code-generator -I/Users/selsta/dev/monero-gui/src/QR-Code-scanner -I/Users/selsta/dev/monero-gui/src/zxcvbn-c -I/usr/local/Cellar/libusb/1.0.23/include/libusb-1.0 -I/usr/local/include/hidapi -I/usr/local/opt/openssl@1.1/include -I/usr/local/include -I/usr/include/malloc -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F /usr/local/Cellar/qt/5.15.0/lib --include /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/moc_predefs.h -p qt --output-dep-file -o /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/WTNNEUUVOU/moc_MoneroSettings.cpp /Users/selsta/dev/monero-gui/src/qt/MoneroSettings.h

Output
------
/Users/selsta/dev/monero-gui/src/qt/MoneroSettings.h:51: Error: Undefined interface
```

When replacing MoneroSettings with normal settings:

```
[ 87%] Building CXX object src/CMakeFiles/monero-wallet-gui.dir/TranslationManager.cpp.o
In file included from /Users/selsta/dev/monero-gui/src/TranslationManager.cpp:29:
/Users/selsta/dev/monero-gui/src/TranslationManager.h:32:10: fatal error: 'QObject' file not found
#include <QObject>
         ^~~~~~~~~
1 error generated.
make[3]: *** [src/CMakeFiles/monero-wallet-gui.dir/TranslationManager.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object monero/src/daemon/CMakeFiles/daemon.dir/command_parser_executor.cpp.o
[ 88%] Building CXX object monero/src/daemon/CMakeFiles/daemon.dir/command_server.cpp.o
/Users/selsta/dev/monero-gui/src/main/main.cpp:29:10: fatal error: 'QApplication' file not found
#include <QApplication>
         ^~~~~~~~~~~~~~
In file included from /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/mocs_compilation.cpp:2:
In file included from /Users/selsta/dev/monero-gui/build/release/src/monero-wallet-gui_autogen/EWIEGA46WW/moc_NetworkType.cpp:10:
/Users/selsta/dev/monero-gui/src/NetworkType.h:31:10: fatal error: 'QObject' file not found
#include <QObject>
         ^~~~~~~~~
```

**Comment by xiphon** [comment]
Updated. Had to rework CMake translations handling in a separate second commit.

**Pull request merged**
