### PR TITLE
transaction: async commit

### PR DESCRIPTION
**Pull request by ph4r05**
Addresses #2123, reduces UI freezing on long-lasting operation, improves Trezor experience

### CODE REVIEW

**Comment by selsta** [comment]
This doesn’t seem to work with Ledger, after a successful transaction it begins with the sending process again. I’ll have to investigate further.

**Comment by ph4r05** [comment]
> This doesn’t seem to work with Ledger, after a successful transaction it begins with the sending process again. I’ll have to investigate further.

Do you pls have a log from the signing? Currently, I don't see why it behaves differently for Ledger. It should work in general :/

Did you test also against the master?

**Comment by selsta** [comment]
After trying it again, I can’t reproduce it anymore and seems to work fine with Ledger.

**Comment by ph4r05** [comment]
Just a note: https://github.com/trezor/trezor-firmware/pull/129 significantly improves UX of the Trezor hardware wallet. The device prompts live refresh permission only once.

**Pull request merged**
