### PR TITLE
wizardcreatedevice: cleanup layout

### PR DESCRIPTION
**Pull request by mmbyday**
hw

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Would it perhaps be better if we set a default value for the subaddress lookahead box for hardware wallets? The default value for normal wallets is 50:200, but that would be too high for hardware wallets in my opinion, as it would take a long time to generate the wallet.

**Comment by mmbyday** [comment]
@dEBRUYNE-1 Solid idea. What would you say is a reasonable default value?

**Comment by selsta** [comment]
50:200 is only a problem for Ledger, Trezor works fine.

**Comment by dEBRUYNE-1** [comment]
@mmbyday @selsta - What if we use 3:100 for Ledger (the value being used in the guides) and 50:200 for Trezor then? Also, the values should be overridden if the user manually enters a value in the box.

**Comment by mmbyday** [comment]
@dEBRUYNE-1 Updated with your recommendations. Thanks.

**Comment by dEBRUYNE-1** [comment]
Thanks!

**Comment by selsta** [comment]
Somehow 3:100 takes longer on my Ledger than 50:200? I’m confused.

**Comment by xmrdsc** [comment]
Nice work, love it.

**Comment by selsta** [comment]
`3:100` takes 72s on my system, `50:200` takes 27s.

**Comment by selsta** [comment]
@mmbyday Can you revert your latest changes? (https://github.com/monero-project/monero-gui/compare/fc8c00287aa097d05993cfa1c75550ee9218a8f9..c0619c37fab399451d36185856428269f5d15879)

We found out that Ledger already uses a lower value by default (5:20), so this change isn’t necessary.

**Comment by mmbyday** [comment]
Thanks for testing! Last change reverted.

**Pull request merged**
