### PR TITLE
Updated appicons.icns

### PR DESCRIPTION
**Pull request by ismhdez**
Modified OSX icons to the new Icon Type (Big Sur) -- It's better integrated in the actual versions of MacOS.

| New Icon | Old Icon |
| -- | -- |
|  |  |

**Dock:**

**Launchpad:**

### CODE REVIEW

**Comment by selsta** [comment]
Could you take a look at https://github.com/monero-project/monero-gui/pull/3560 ? Which one do you prefer?

**Comment by ismhdez** [comment]
> Could you take a look at #3560 ? Which one do you prefer?

Circled icon should not be the default one anymore, since macOS Big Sur all icons were changed to rounded squares:
Concept

I think my suggestion fits more with the new macOS look, the app name should be "Monero Wallet.app" or something like that too, yes.

**Comment by ismhdez** [comment]
Any news regarding the PR?

**Comment by selsta** [comment]
It takes a while until things get merged.

**Review by selsta — COMMENTED** [review]
Please rebase and set file permission to 644

**Comment by ismhdez** [comment]
Fixed, rebased and fixed file permissions (appicon.icns -> 644)

**Comment by selsta** [comment]
Do you know how to squash?

**Comment by ismhdez** [comment]
> Do you know how to squash?

Uhm, nope

**Comment by selsta** [comment]
git rebase -i HEAD~2

then set the second commit to "s" for squash and force push.

**Comment by ismhdez** [comment]
> git rebase -i HEAD~2
> 
> then set the second commit to "s" for squash and force push.

Should I do the git rebase from the upstream, right? (git rebase -i HEAD~2 upstream/master)

**Comment by selsta** [comment]
just git rebase -i HEAD~2 should work

**Comment by ismhdez** [comment]
If I do the rebase like you're saying, the appicon.icns file is the one I'm requesting, so I cannot commit it again. What do you want me to is a rebase from your fork (where the appicon.icns is different), and commit mine's with file permission as 644? (squash & force push) 🤔

**Comment by selsta** [comment]
basically I want 1 commit that doesn't have any merge conflicts

**Comment by ismhdez** [comment]
> basically I want 1 commit that doesn't have any merge conflicts

That commit is ok for you?

**Comment by selsta** [comment]
yes, thanks

**Pull request closed without merging**
