### PR TITLE
main.qml: Light theme by default

### PR DESCRIPTION
**Pull request by SomaticFanatic**
#2430

### CODE REVIEW

**Comment by selsta** [comment]
I think this should wait until we improve the contrast on the white theme a bit, IMO it’s not perfect to read at the moment.

**Comment by SomaticFanatic** [comment]
What part of the lighter theme do you feel needs a better contrast? The font?

**Comment by erciccione** [comment]
> Edit: We should just merge this and work on the light themes design in a future PR

I disagree. Using the white theme as default was discussed (and rejected) at the time the black theme was introduced. If we want to switch back to using the white theme as default, the design should be optimized before, not after.

**Comment by elibroftw** [comment]
Can we close this and the related issue? If anything the default theme should be the system's theme and then dark theme as it is more readable. Light theme by default only exists because white is the default background. If #121212 was the default background color in the HTML spec when the web first launched, then this discussion wouldn't even be a thing 😂. 

It's been 3 years now.

**Pull request closed without merging**
