### PR TITLE
ContextMenu: styling, implement ContextMenuItem component

### PR DESCRIPTION
**Pull request by xiphon**
context-menu-styling

### CODE REVIEW

**Comment by selsta** [comment]
```
selsta@mbpR ~/d/monero-gui> build/release/bin/monero-wallet-gui.app/Contents/MacOS/monero-wallet-gui
2019-11-19 07:15:44.408	W app startd (log: /Users/selsta/Library/Logs/monero-wallet-gui.log)
2019-11-19 07:15:44.409	W Qt:5.13.2 GUI:- | screen: 1440x900 - dpi: 72 - ratio:0.863281
2019-11-19 07:15:44.710	W QQmlApplicationEngine failed to load component
2019-11-19 07:15:44.710	W qrc:/main.qml:1501 Type PasswordDialog unavailable
2019-11-19 07:15:44.710	W qrc:/components/PasswordDialog.qml:190 Type MoneroComponents.Input unavailable
2019-11-19 07:15:44.710	W qrc:/components/Input.qml:49 Type MoneroComponents.ContextMenu unavailable
2019-11-19 07:15:44.710	W qrc:/components/ContextMenu.qml:33 Type MoneroComponents.ContextMenuItem unavailable
2019-11-19 07:15:44.710	W qrc:/components/ContextMenuItem.qml:12 Cannot override FINAL property
2019-11-19 07:15:44.710	E Error: no root objects
```

**Comment by xiphon** [comment]
Updated, does it fix the issue?

**Comment by selsta** [comment]
same issue

**Comment by xiphon** [comment]
Ah, you are using the latest Qt version instead of 5.9.
Anyway, updated once again, fixed.

**Pull request merged**
