### PR TITLE
images: remove unused images

### PR DESCRIPTION
**Pull request by selsta**

### CODE REVIEW

**Comment by luigi1111** [comment]
@selsta please rebase.

**Comment by selsta** [comment]
rebased

**Comment by xmrdsc** [comment]
@selsta `images/moneroLogo_white.png` is used since recent Merchant merge. Would you mind removing that one from the list?

**Comment by selsta** [comment]
@xmrdc updated

**Comment by luigi1111** [comment]
@selsta :)

**Pull request merged**
