### PR TITLE
SettingsLog: disable daemon command input in Remote Node mode 

### PR DESCRIPTION
**Pull request by xiphon**
Closes https://github.com/monero-project/monero-gui/issues/3228

### CODE REVIEW

**Comment by selsta** [comment]
Hmm, that also disabled the option to change log level.

**Comment by xiphon** [comment]
> 
> 
> Hmm, that also disables the option to change log level.

Updated, hiding just daemon console and command input now.

**Comment by xiphon** [comment]
Updated. Disables daemon command input in Remote Node mode now.

**Review by selsta — APPROVED** [review]

**Comment by alberto-fc** [comment]
This fixed #3228 as-is, what I like is the simplicity of it because remove that confusing option and really you shouldn't be using the GUI to execute Commands in the Remote daemon, even if it is **your** daemon.

Nice and elegant!

**Pull request merged**
