### PR TITLE
AppWindow: append wallet name to window title

### LINKED ISSUE #2459: Add wallet name to window title
Wallet name is not included in window title. 

Current window title in Windows is always Monero. I suggest renaming to "**Monero - _Wallet name_**".

This would be useful when custom decorations are disabled and when multiple instances are running.
image

### PR DESCRIPTION
**Pull request by xiphon**
Closes #2459

### CODE REVIEW

**Comment by selsta** [comment]
Does a zero length string evaluate as false in JS?

**Comment by jonathancross** [comment]
This can lead to strange results if `walletName` ever ends up as `null` or `false`:
```
var walletName = null
"Monero" + (walletName && " - " + walletName)
"Moneronull"

var walletName = false
"Monero" + (walletName && " - " + walletName)
"Monerofalse"
```

Maybe better to be explicit?
```
"Monero" + (walletName ? " - " + walletName : "")
```

**Comment by xiphon** [comment]
> This can lead to strange results if `walletName` ever ends up as `null` or `false`:

You can't set `walletName` to `null` or `false`.

**Comment by xiphon** [comment]
Anyway, i do agree, better to use some typical syntax for this. Updated.

**Pull request merged**
