### PR TITLE
[Qt 5.9] Adding pricing/fiat conversion functionality (updated)

### PR DESCRIPTION
**Pull request by selsta**
See #1714 for the original discussion.

### CODE REVIEW

**Comment by mmbyday** [comment]
Great work. 
Functionality works fine on linux build, but on a Windows build the currency dropdown has issues. Still investigating.

**Comment by selsta** [comment]
@mmbyday Deleting and editing works fine on my system.

**Comment by selsta** [comment]
Different Qt version on Windows? Working fine herey

**Comment by mmbyday** [comment]
Possibly.  If only the buildbot could kick off a proper build with "release" and this pricing/fiat enhancement.

**Comment by selsta** [comment]
@mmbyday Buildbot build should now be working.

**Comment by mmbyday** [comment]
@selsta Tested buildbot's win64 build 33cb188 and the same issue occurs.  
bb

Getting these type of errors in the log

```
WARN 	frontend	src/wallet/api/wallet.cpp:367	qrc:///components/StandardDropdown.qml:195: Error: qsTr(): first argument (sourceText) must be a string
ERROR	frontend	src/wallet/api/wallet.cpp:371	data : internal error: no currency info for index  3
WARN 	frontend	src/wallet/api/wallet.cpp:367	convert : convert() called while price is stale (last updated:  "" )

**Comment by selsta** [comment]
That’s weird... Thanks for testing.

**Comment by selsta** [comment]
@mmbyday Currency names are defined as `QStringLiteral`. It seems like Qt 5.6 doesn’t support `qsTr()` with `QStringLiteral`. Considering that we’ll update to Qt 5.9, I won’t bother fixing this.

**Comment by selsta** [comment]
#2141

**Pull request closed without merging**
