### PR TITLE
Czech translation added

### PR DESCRIPTION
**Pull request by ruzaq**

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks for this translation, but you need to edit a couple more files when adding a new language. At the end your pull request should look like [this one](https://github.com/monero-project/monero-gui/pull/836/files), with the same files edited, but adapted for czech and with the right flag. If you need support to do so, let's chat on `#monero-translations` (irc-freenode, matrix/riot, slack)

**Comment by ruzaq** [comment]
Thanks for the info. I've made a required changes best to my knowledge.

**Comment by erciccione** [comment]
Looks good except for the flag, cannot see it. don't know if it's a GitHub's bug. Will test this PR tomorrow

**Comment by erciccione** [comment]
This Pr is broken. Can you remove the last commit?

**Comment by ruzaq** [comment]
I've recreated last commit. Now it has no conflict.

**Comment by erciccione** [comment]
Ok, squash again please

**Comment by erciccione** [comment]
Hey @ruzaq it's a pity that this pr is closed now, you did a lot of work. Do you need help reopening it?

**Comment by seberm** [comment]
Oh, what happened here? Why the commits are missing?

@ruzaq It would be great if you could try to reopen/resubmit this PR. Is it possible?

@erciccione If you need any help with czech translations I am also able to help you.

**Comment by ruzaq** [comment]
I've made some mistake on squash. How could I reopen/resubmit this PR?

**Comment by ruzaq** [comment]
I've just recreated 2 related commits into my fork.

**Comment by erciccione** [comment]
Thanks for reopening this, but probably the languages.xml file was updated and now you have a conflict. Can you solve it and then squash in one commit?
Come on #monero-translations if you need any support

**Comment by ruzaq** [comment]
Everytime i squashed a kitten and my hope that i understand git dies.

**Comment by seberm** [comment]
Hello @ruzaq,
it's necessary to do a rebase on top of the monero-gui/master (not a merge).

You need to reset your merge commit:
```
$ git reset --hard HEAD~1
```

Add and fetch and rebase
```
$ git remote add monero https://github.com/monero-project/monero-gui.git
$ git fetch monero
$ git rebase monero/master
```

Now you have to resolve the conflict in lang/languages.xml
```
...
$ git add lang/languages.xml
$ git rebase --continue
Applying: +czech translation
Applying: czech translation updated
```

Your changes should be now rebased on top of the (original) monero-gui/master branch. I did these steps for you.

@erciccione I resolved a conflict in my forked repository. Is it possible to merge it from there?
- https://github.com/seberm/monero-gui/commits/master

**Comment by ruzaq** [comment]
I repeated the procedure as described by seberm. Thanks for help.

**Comment by seberm** [comment]
Great! But there is still one problem - you forgot to resolve the conflict in lang/languages.xml :). It is what I meant by three dots. It's my mistake. I should explain it more clearly.

- See the commit here: https://github.com/monero-project/monero-gui/pull/1009/commits/24f6ccd0d90228359e40644539a1a52f7758acb7

Now you have to fix your 24f6ccd0d commit.

On top of your master, run:
```
$ git rebase --interactive 64ce0e62
```
This command will open an editor with this content:
```
pick 24f6ccd +czech translation
pick a37f03c czech translation updated
...
```
Tell the git-rebase that you want to edit (24f6ccd) commit. Change the first line to:
```
edit 24f6ccd +czech translation
pick a37f03c czech translation updated
```
Save and exit the editor.

Fix the content of lang/languages.xml file:
```
vim lang/languages.xml
--> resolve the conflict on lines 41-47.
--> save and exit your text editor
```
After that add and commit the changes:
```
$ git add lang/languages.xml
$ git commit --amend
--> save and exit the text editor
$ git rebase --continue
```

Now you should review your changes:
```
$ git log -p -2
```

If everything is ok, push the changes (--force push will be needed):
```
$ git push --force origin master
```

**Comment by erciccione** [comment]
@seberm 
Thank you for taking care of this pr. If you have fixed everything in your repo, you can make a pr from your branch pointing at ruza's master, then he will have to merge it using the 3d option ('rebase and merge') so we are sure there are no merge commits on our way.

**Comment by ruzaq** [comment]
I did everything I've been asked to. Hope it enough :)

**Comment by erciccione** [comment]
@luigi1111 this is ready to go

**Pull request merged**
