### PR TITLE
Minor adjustments to the Swedish translation

### PR DESCRIPTION
**Pull request by snaggen**
When I audited the GUI i found some Swedish translations that were not optimal. 
* Layout was translated as Layout in Swedish, which is not really optimal but works. However, since it really is not about Layout, I changed the Swedish translation to "Utseende" since that better fits the Swedish language and what the page is really about. 
* Sweep Unmixable is a strange sentence to start with, but it was translated to "Svep upp omixbara" which feels like a word by word translation. I interpret the word "Sweep" here as the metaphor where you are sweeping the floor, so you are basically cleaning up the unmixables. So I have adjusted the swedish translation to better fit this metaphor. 
* Also I have changed a string on the Settings Info page to make it more consistent. 

@freminik @ordtrogen can you review this.

Also, I must say that the Swedish translation looks very good. So even if we don't have agreed on everything, the result is still really good... and after all, that is what matters. So kudos for your efforts.

### CODE REVIEW

**Comment by snaggen** [comment]
I also sent a note on the swedish translator list tp-sv@listor.tp-sv.se

**Comment by ordtrogen** [comment]
Do you mean "Layout" is incorrect in the English source?

**Comment by snaggen** [comment]
Well, basically yes, since the only option there is about client side decorations. So, Appearance would probably be a better source. However, since Layout in Swedish use is imported from English it feels even worse in Swedish, since it is used in a much more narrow scope. Hence, I took the liberty to change it, but I should probably open a bug against the original translation.

**Comment by snaggen** [comment]
Opened issue #1666

**Comment by snaggen** [comment]
Updated the translation based on review by Anders on the translation list tp-sv@listor.tp-sv.se.

**Pull request merged**
