### PR TITLE
password dialog: show error in place

### PR DESCRIPTION
**Pull request by xiphon**
password-fix

### CODE REVIEW

**Comment by sectioneight** [comment]
Merging duplicate #1694 in here -- same issue

**Comment by xiphon** [comment]
@sectioneight 
is not a duplicate, is a fix to resolve the issue #1694. Is absolutely correct to have both #1699 (issue) and #1699 (pull request) open and close #1699 once it gets merged.

**Comment by sectioneight** [comment]
Gotcha. Would you like help on #1694, or is the PR for this issue going to address both?

**Comment by dEBRUYNE-1** [comment]
@xiphon - Could you PR this against the `release-v0.13` branch too?

**Pull request merged**
