### PR TITLE
Add MacPorts compatibility

### PR DESCRIPTION
**Pull request by IPGlider**

### CODE REVIEW

**Comment by jtgrassie** [comment]
Why hardcode library search path? What about users who may have MacPorts but wish to sue system installed libraries or use homebrew? Surely best left to the person compiling what search paths to use.

**Comment by IPGlider** [comment]
Changed order and check.

Homebrew paths are already hardcoded therefore having default MacPorts paths hardcoded follows the same pattern.

Having MacPorts as a fallback to Homebrew does not interfere with the current behaviour for Homebrew users and makes things easier to MacPorts devs.

**Comment by jtgrassie** [comment]
You're missing my point. The search paths shouldn't be hardcoded, they should be defined by the system environment or specified / overridden by the person compiling.

**Comment by selsta** [comment]
Not sure what to do with this, how do other projects support both homebrew and MacPorts?

**Comment by jtgrassie** [comment]
@selsta 
> how do other projects support both homebrew and MacPorts?

They do not hardcode library paths. If any paths are added, they are just hints like `/usr/, /usr/local, /opt/local`. This PR can probably be merged though as a stop-gap until this has been properly refactored.

**Pull request closed without merging**
