### PR TITLE
[Qt 5.9] qrscanner: enable by default

### PR DESCRIPTION
**Pull request by mmbyday**
Lack of QR scanning capability is a major inconvenience when moving funds. i.e. sending from GUI to a mobile wallet or paper wallet/offline wallet.

Before this is merged,
- verify working on buildbots / build environment
- verify readme works on MacOS as is, or if further updates required.
- depends on #1807

Thoughts?

### CODE REVIEW

**Comment by selsta** [comment]
Don’t really know how to get this to compile on macOS. (`brew install zbar` didn’t work). I’ll look into it tomorrow.

**Comment by xmrdsc** [comment]
Cool! UX needs some work though (buttons look weird). Don't you agree?

**Comment by mmbyday** [comment]
@xmrdc are we lboth looking at the "after" with qrcode icons? The "before" did look weird ;-)

**Comment by selsta** [comment]
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -stdlib=libc++ -fPIC -fstack-protector -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -O2 -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC -DWITH_SCANNER -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../monero-gui -I. -I../monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../monero/src -I../src/QR-Code-scanner -I/usr/local/Cellar/qt/5.12.0/lib/QtQuick.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtMultimedia.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtQml.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.12.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.12.0/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.12.0/lib -o QrScanThread.o ../src/QR-Code-scanner/QrScanThread.cpp
In file included from ../src/QR-Code-scanner/QrScanThread.cpp:29:
../src/QR-Code-scanner/QrScanThread.h:38:10: fatal error: 'zbar.h' file not found
#include <zbar.h>
         ^~~~~~~~
1 error generated.
make: *** [QrScanThread.o] Error 1
```

`zbar.h` is in `/usr/local/include`

**Comment by selsta** [comment]
@mmbyday cleaning the build first worked, thanks. Still, I’m against merging this until we fix #611 and improve the overall UI (there is no way to close the scanner).

**Comment by mmbyday** [comment]
@selsta #611 should be fixed now. Camera no longer loads for a split second during startup.

**Comment by selsta** [comment]
@mmbyday Can confirm :) IMO we should look into adding this after v0.14.1.0 is out, as it will require build bot changes.

**Comment by mmbyday** [comment]
@selsta  Great :) Also added a font awesome button so there's an obvious way to close the scanner.

**Comment by jonathancross** [comment]
> IMO we should look into adding this after v0.14.1.0 is out, as it will require build bot changes.

Friendly ping... v0.14.1.0 is out :-)

**Comment by selsta** [comment]
soon™ :)

**Comment by jonathancross** [comment]
This needs a rebase.

Anything else still required (eg buildbot changes?)

**Comment by selsta** [comment]
This is not relevant anymore, qr scanner code has changed significantly.

**Pull request closed without merging**
