### PR TITLE
flickable for wizardController

### LINKED ISSUE #2048: Scrolling for the wizards
> I'm on a tiny screen and I'm trying to connect to a remote node in the GUI. But the connect button is not visible in the new version of the monero software. There is no scroll button.
> Does anybody know what to do?

### PR DESCRIPTION
**Pull request by xmrdsc**
Scrolling like in `middlePanel.qml`

Fixes #2048

### CODE REVIEW

**Comment by selsta** [comment]
Somehow I don’t see a scrollbar on macOS.

**Comment by xmrdsc** [comment]
@selsta good catch, it fell outside of the window. Fixed.

**Comment by mmbyday** [comment]
Works pretty good!

There might be a height issue during the create new wallet flow in the daemon settings screen.

errrrr

Incidentally, the language settings screen is not scrollable yet.

**Comment by xmrdsc** [comment]
Oh, good point @mmbyday. Ill have to look into that. Thanks!

**Comment by xmrdsc** [comment]
Seems to be a problem with the `RemoteNodeEdit{}` component regarding calculation of heights (?). Did not want to dive into it right now, rather fix it pragmatically.

As for language screen, it was a quick addition due to language sidebar not working. Will fix in another PR ;)

Scrolling for wizards are now working.

**Pull request merged**
