### PR TITLE
Wallet password dialog refactoring + allow password to be changed

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by luigi1111** [comment]
@stoffu Please rebase (or wait if some of the merges I'm going to do will conflict again).

**Comment by stoffu** [comment]
@luigi1111 Rebased with changes conforming to the recent redesign in #826 
CC: @Jaqueeee

**Comment by stoffu** [comment]
@Jaqueeee I did quite a bit of refactoring regarding the wallet password dialog, such that a single instance of `passwordDialog` can be reused for any purposes. I've also changed the behavior at the app launch where previously it tried to read the file with an empty password, which is removed now and instead a dialog box is shown immediately.

Please check if I didn't screw up things.

**Comment by skftn** [comment]
Running your branch: 

- Opened GUI
- Created new wallet
- Changed password from within the GUI
- Closed GUI - Opened GUI
- Entered new password - works

Trying the wallet on the CLI:
- `monero-wallet-cli --testnet `
- password prompt, new password works

**Comment by skftn** [comment]
@stoffu do you think the changes to the `PasswordDialog` will affect other parts of the GUI? If not, I'm all for merging this.

**Pull request merged**
