### PR TITLE
Add hardware wallet device supported models

### PR DESCRIPTION
**Pull request by rating89us**
Being more specific about the supported models to avoid issues like #2685 in the future.

### CODE REVIEW

**Comment by rating89us** [comment]
Done

**Comment by selsta** [comment]
Do you know how to squash your commits together?

**Comment by rating89us** [comment]
No, I don't. Can you do it for me?

**Comment by selsta** [comment]
I’ll PR it for you.

**Comment by rating89us** [comment]
> 
> 
> I’ll PR it for you.

See #2694

**Pull request closed without merging**
