### PR TITLE
Makefile: set CMAKE_BUILD_TYPE to debug for debug target

### PR DESCRIPTION
**Pull request by selsta**
https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

> Typical values include Debug, **Release**, RelWithDebInfo and MinSizeRel, but custom build types can also be defined.

> Depending on the situation, the value of this variable may be treated **case-sensitively** or case-insensitively.

### CODE REVIEW

**Comment by selsta** [comment]
@mj-xmr please review

**Review by mj-xmr — APPROVED** [review]
It looks ok from the perspective of the task and its description, but could you explain why we are setting `Release` in the first place, while the directory name and the target name are both `debug`?

**Comment by selsta** [comment]
Good question, I just checked for typos. Will update to debug.

**Comment by selsta** [comment]
@mj-xmr updated

**Review by mj-xmr — APPROVED** [review]

**Pull request merged**
