### PR TITLE
workflows: upload Windows and Linux static binaries

### PR DESCRIPTION
**Pull request by xiphon**

### CODE REVIEW

**Comment by selsta** [comment]
Opinion on only uploading daemon and gui?

**Comment by xiphon** [comment]
> Opinion on only uploading daemon and gui?

Yep, updated.

**Review by selsta — APPROVED** [review]

**Comment by Snipa22** [comment]
Merge confict, please resolve!

**Comment by xiphon** [comment]
Resolved

**Review by selsta — APPROVED** [review]

**Pull request merged**
