### PR TITLE
[Qt 5.9] Remove scaleRatio

### PR DESCRIPTION
**Pull request by xmrdsc**
Removing `scaleRatio`, it is not needed. To scale the GUI; use environment variable `QT_SCALE_FACTOR`. There is commented code in [main.cpp](https://github.com/monero-project/monero-gui/blob/master/main.cpp#L99) that deals with DPI. And for mobile #2026 is a better idea.

Requires white-theme https://github.com/monero-project/monero-gui/pull/2060

### CODE REVIEW

**Comment by twiuglufosfa** [comment]
after removing scaleratio i enabled highdpi on main.cpp and QT_SCALE_FACTOR on pro

 but is not working on android.

before removing scaleratio everything was ok.

i try all on QT_SCALE_FACTOR (1,2,1.3 etc)

**Comment by xmrdsc** [comment]
@twiuglufosfa Android is unsupported, please see #2026

**Comment by twiuglufosfa** [comment]
android was working very well with scaleratio

the only changed needed was ref_dpi on main.cpp

after removing scaleratio and inserting QT_SCALE_FACTOR on pro file

 resolution wont change so maybe i dont put right prices on QT_SCALE_FACTOR

or QT_SCALE_FACTOR dont work!

**Comment by selsta** [comment]
Can you try adding `qputenv("QT_SCALE_FACTOR", "1.5");` to main.cpp?

**Comment by twiuglufosfa** [comment]
worked!

thnx a lot.

**Pull request merged**
