### PR TITLE
Russian Language GUI Update for v0.12.1

### PR DESCRIPTION
**Pull request by erciccione**
This is erciccione/monero-core#3
It was opened on my repo by mistake and i saw it only today. It's technically correct and can be merged.

### CODE REVIEW

**Comment by erciccione** [comment]
@LvMsterfild can you approve this PR if everything is alright?

**Comment by luigi1111** [comment]
I would prefer someone to look over the actual translations (your review of the PR is fine on the technical side).

**Comment by erciccione** [comment]
Will ping someone of the russian community

**Comment by erciccione** [comment]
@LvMsterfild Could you ask on the chat of the russian community if somebody can review this PR please?

**Comment by luigi1111** [comment]
I'm going to go ahead and include this; @erciccione if you can note to seek a review/updates from the Russian community at some point, that would be great.

**Comment by LvMsterfild** [comment]
Was some little bugs in translation. Can I fix it yet ?

2018-05-23 23:47 GMT+03:00 luigi1111 <notifications@github.com>:

**Comment by erciccione** [comment]
@LvMsterfild open a PR, if done in time maybe it can make it for the release

**Pull request merged**
