### PR TITLE
Dutch translation of GUI text added in January

### PR DESCRIPTION
**Pull request by ProkhorZ**
Plus a few corrections of older translations.

@fridzema already submitted another Dutch translation, so you're able to choose!
Who wants to review both translations and choose the best one, or suggest edits?
@rpcjacobs @potatored @dnaleor @dEBRUYNE-1

### CODE REVIEW

**Comment by ProkhorZ** [comment]
Other Dutch translation: https://github.com/monero-project/monero-gui/pull/1127

**Comment by erciccione** [comment]
Hi @ProkhorZ thank you for your work, but i don't think it's fair to ask @fridzema to close its PR and lose his work, especially when he opened his PR first. I suggest to use one of the 2 PRs as base and to include changes from the other one. One of the two can add the other one as collaborator on the repository, so that he can push changes directly to the PR. 
You and @ProkhorZ can discuss what to include and from where directly on one of this PRs or on the chat of the Localization workgroup: `#monero-translation`

What do you think about this solution?

**Comment by fridzema** [comment]
@erciccione I don't really care. Currently don't have enough time to complete the translations so i think @ProkhorZ can continue this if he wants.

**Comment by erciccione** [comment]
Ok @fridzema , in this case better close your PR, if you don't plan to work on it, in favour of this one. if you want to integrate some of your changes you can discuss here. Thanks

**Comment by potatored** [comment]
I will have a look at it when im back from holiday next week!

Greets Potatored

Op 20 feb. 2018 21:29 schreef "ProkhorZ" <notifications@github.com>:

**Comment by ProkhorZ** [comment]
Hi @erciccione, I will take a detailed look at the other translation this weekend and I will edit mine where it can be improved.

In general, I hope we will choose the best contribution rather than the first. I should be able to create a better translation since it was my day job until recently, I announced it before I started and I delivered a complete one.

**Comment by ProkhorZ** [comment]
Thanks, @potatored! 

@erciccione This is the final version if it's up to me. I changed one term following @fridzema's translation, and I took a closer look at the hotkeys in the left panel. Is it technically OK?

**Pull request merged**
