### PR TITLE
TitleBar: add close wallet button

### PR DESCRIPTION
**Pull request by selsta**
Screenshot 2019-09-16 at 23 57 15
To be used in combination with: #2383

### CODE REVIEW

**Comment by selsta** [comment]
also ping @Realchacal

**Comment by Realchacal** [comment]
Extremely nice!

Just to understand it: You don't like the `x` because we already have a `x` in the titlebar, right?
image
That's a valid argument. Not sure if it's enough to outweigh the reduced intuitiveness, though.

**Comment by selsta** [comment]
Yes, 2 x icons would be bad IMO. Sign out is similar to the one we already have and was the best I found on fontawesome.

**Comment by Realchacal** [comment]
Ok! One last thing: IMO the moon is a **LITTLE** bit too big. (I know it's exactly the same height as the globe, but to my eye it looks too big, though.)

**Comment by selsta** [comment]
I reduced the moon font size by 1 point.

**Comment by Realchacal** [comment]
I already had noticed it in your other screenshots ;) LOOKS SO MUCH BETTER!!!

**Comment by Realchacal** [comment]
Fixes #2339

**Comment by luigi1111** [comment]
@selsta please rebase.

**Comment by selsta** [comment]
@luigi1111 done

**Pull request merged**
