### PR TITLE
Update Brazilian Portuguese translations for #1116

### PR DESCRIPTION
**Pull request by netrik182**

### CODE REVIEW

**Comment by netrik182** [comment]
Yes, I can do it tonight.

**Comment by netrik182** [comment]
I'm still learning how to use git. I have now all the changes into a single commit in my repository, but do I have to open a new PR?

**Comment by erciccione** [comment]
If you squashed locally, you only need to force push to your remote repository, you can do that using 'git push -f'

**Comment by netrik182** [comment]
I did so :) can you check if everything's alright?

**Comment by erciccione** [comment]
No, looks like everything is the same, try using `git rebase -i HEAD~3` and then squash

**Comment by netrik182** [comment]
@erciccione I don't have the 3 commit in my repo nor locally anymore, sorry. Could you close this issue/PR and I submit a new PR? (I had a copy of the file saved in another folder, so I cloned the repo again and did all the changes in one commit.)

**Comment by erciccione** [comment]
No problem, i cannot close your PR but you can, using the "close" button. You can just open a new PR with one single commit. Thanks

**Comment by netrik182** [comment]
Just sent the new PR #1152

**Pull request closed without merging**
