### PR TITLE
keys: dynamic panel height and qrcode is no longer clipped

### PR DESCRIPTION
**Pull request by mmbyday**
**Before:**
a

**After:**
b

### CODE REVIEW

**Comment by selsta** [comment]
with the patch there is a lot of empty space beneath the QR code, is this necessary?

**Comment by mmbyday** [comment]
Thanks! Open to other suggestions, but this was the best combo of settings that would also allow the mobile sized (aka minimum width window) window to also work :)

**Comment by selsta** [comment]
Even on the smallest window there is this space beneath the QR code on macOS. Is this how it’s supposed to look?

screenshot 2018-11-29 at 23 34 14

**Comment by mmbyday** [comment]
Good eye.
Updated with a 100px offset. 180px was added previously because that was the qr image's minimum height.
aft

**Comment by selsta** [comment]
Looking good now. Can you squash your commits?

**Pull request merged**
