### PR TITLE
Update monero-core_pt-br.ts

### PR DESCRIPTION
**Pull request by EvertonMelo**
revisado até linha 440; 
audited to line 440;

Pending suitability for latin1;

### CODE REVIEW

**Comment by erciccione** [comment]
Thank you, but there is already an open PR for the same file: #1136 
Can you close this PR and help reviewing #1136 ?

**Comment by EvertonMelo** [comment]
@erciccione 

hi, 

It was not me who created this PR #1136 
but I gave continuity to it.

**Comment by erciccione** [comment]
@EvertonMelo I know you didn't open it, that's why i'm asking you to close this one :)

1136 was opened before this PR, so would be great to work directly on that PR. Maybe you can suggest your changes there.

**Comment by EvertonMelo** [comment]
@erciccione 

this struture never run on windows:
https://github.com/monero-project/monero-gui/commits/master/translations/monero-core.ts 

this solutions is: #1141

**Comment by erciccione** [comment]
Pleas close this PR in favor of #1152

**Comment by EvertonMelo** [comment]
@erciccione 

PR for windows never compile on tests:
#1141 ( read please! )

the first PR **monero-core.ts**

https://github.com/monero-project/monero-gui/commit/10a09c1d28a95cb00d379227037d15a19475c9a2#diff-fc4dfb4503e80c18021f3874a6132240 ( 02/12/2016 )
not compile for windows-amd64. 

My PR add more translate for #1152 

I close the this PR, if everyone sent it to "monero-core.ts tb do this."

**Comment by erciccione** [comment]
@EvertonMelo 
yes, windows builds are broken, and wil be fixed by that commit.

The point here is: do this pr conflict with #1152 in any way or it's just an integration? if you pulled 1152 and based this PR on that PR, please add "Requires #1152 " somwhere in the descritpion or title. Otherwise, you will have to close this or it will conflict with 1152

**Comment by EvertonMelo** [comment]
I will close this PR.
if they do not solve, in exactly one month.

I'm going to open 3 PR.

monero-core.ts;
monero-core-en.br
monero-core-en.pt

and I will ignore qq supplicar to close a PR of someone who is working and not absent or stopped.

**Pull request closed without merging**
