### PR TITLE
Added some retina icons

### PR DESCRIPTION
**Pull request by GBKS**
As requested by selsta.

### CODE REVIEW

**Comment by selsta** [comment]
Thank you! :) Looks like next release will have awesome retina graphics.

Can you squash your commits?

**Comment by selsta** [comment]
#1881

**Comment by GBKS** [comment]
Sounds good about the qml.rc entries. Thank you.

How do I squash commits? That's where my Github knowledge ends, and the help section is not particularly helpful.

**Comment by selsta** [comment]
I did everything in #1881 (you are included as the author :)), you can close this PR.

**Comment by GBKS** [comment]
Cool, thanks.

**Comment by selsta** [comment]
I usually squash like this:
- `git reset --soft HEAD~3`
- `git commit`

This squashes the last 3 commits together.

**Pull request closed without merging**
