### PR TITLE
remove colored dots

### LINKED ISSUE #2573: Menu: colored dots aren't consistent with wallet's design
After removing the color stripe at the top (#2527), we should also remove colored dots in Menu.

Current:
image

After:
image

### PR DESCRIPTION
**Pull request by tobtoht**
closes #2573

### CODE REVIEW

**Comment by tobtoht** [comment]
Comparison:

gui_dots_before
gui_dots_after

IMO dots removed gives a cleaner look that is more in line with the rest of the UI.

**Comment by selsta** [comment]
> IMO dots removed gives a cleaner look.

Agree, it does look slightly cleaner but I think it worsens the UX. The colored dots allow you to quickly see which menu you have selected and they can also help find the menu item you are looking for. Just text is IMO a bad menu.

What do you think about replacing the dots with minimalistic icons? See Github as an example:

Screenshot 2019-12-17 at 00 38 55

Also ping @rating89us

**Comment by tobtoht** [comment]
There are currently 3 indicators for the selected item: the dot with the arrow, the highlighted '>' and the color gradient. I find that with the dots removed it is not any harder to see which item is selected.

I agree with your point on quickly being able to find a menu item, although I don't think the colored dots aid in that regard as it is now. I'm not opposed to replacing the dots with icons if they represent the tab in a meaningful way.

**Comment by selsta** [comment]
If you want to update this PR for now can you change the left margin between the app border and menu text to be the same as the balance card? (Setting it to the half of the current value).

**Comment by tobtoht** [comment]
Slightly more flush to the eye with 22 pixels instead of 20.

**Comment by rating89us** [comment]
Maybe increase the gray in the black-gray gradient to better highlight the selected item

image

**Comment by tobtoht** [comment]
gui_dots_line_1

vs.

gui_dots_line_2

Which one do you think is better?

**Comment by rating89us** [comment]
I like the 2nd one.

And what if we also select Send when Address book is selected?
image

**Comment by tobtoht** [comment]
gui_dots_removed_1

How's this?

**Comment by rating89us** [comment]
Looks good to me

**Comment by rating89us** [comment]
You forgot the orange bar

**Comment by tobtoht** [comment]
It's the Rectangle in MenuButton.qml

**Comment by rating89us** [comment]
Ok, sorry

**Comment by selsta** [comment]
Orange bar is an improvement. Still curious what others think, I’m ok with it.

**Comment by selsta** [comment]
dEBRUYNE prefers the dots but is ok with this change. What is your opinion @xiphon ?

**Pull request merged**
