### PR TITLE
Translations from Weblate

### PR DESCRIPTION
**Pull request by erciccione**
https://translate.getmonero.org/projects/monero/gui-wallet/

Translation files updated:

```
    Found 724 source text(s) (2 new and 722 already existing)
    Removed 2 obsolete entries
```

Translators:

* Spanish

    * Luis Alejandro Herrera Bolaños
    * ian vatega
    * Miguel Medina
    * Michael Russo
    * Samuel
    * 0x82b
    * kombometralla
    * Tony Nguyen

* Slovak

    * Boris Sipos

* Vietnamese

    * Tabula Rasa

* Italian

    * 8uDD4T
    * Gleb Golov

* Chinese (Traditional)

    * Lafudoci

* Catalan

    * Joan Montané

* Persian

    * Nima Ghotbi

* Esperanto

    * Gilberto F da Silva

* Russian

    * Russian Bear
    * Agent LvM
    * v1docq47

* Japanese

    * Scott Anecito
    * x52fws
    * Lana

* Portuguese (Portugal)

    * Demofrager
    * Ian appel
    * EvolBit

* French

    * Bertrand Jacquin
    * lir4376
    * Loué Marie
    * el00ruobuob

* Czech

    * Michal Vašíček
    * dskch83

* Polish

    * ambercookie

* Greek

    * warraxxx
    * Georgios Apostolopoulos
    * ΚΥΡΙΑΚΟΣ ΚΑΡΑΚΥΡΙΟΣ
    * Marinus Savoritias
    * Iason Andreou
    * Donald A. Iljazi

* Lithuanian

    * Vytas
    * Aivaras Kasperaitis

* Portuguese (Brazil)

    * Renato MB
    * netrik182
    * Mathkamy

* Norwegian Bokmål

    * Allan Nordhøy

* Dutch

    * obit33
    * Edwin den Boer
    * dutchcodes

* Hebrew

    * Ori Levenglick
    * Yan Abu Arab

* German

    * G. Orwell
    * mr
    * Paul Janowitz
    * Nicolas
    * GreenPiece
    * SJ
    * Deleted User
    * Wobole

### CODE REVIEW

**Review by xiphon — APPROVED** [review]

**Comment by selsta** [comment]
This fails to compile. One of the files is not correctly formatted.

```
lrelease error: Parse error at /monero-gui/translations/monero-core_he.ts:1511:2: Unexpected '<'.
1365
```

**Comment by erciccione** [comment]
Fixed. The buildbots seem to fail for unrelated reasons.

**Comment by selsta** [comment]
lrelease error: Parse error at /monero-gui/translations/monero-core_hr.ts:1505:2: Unexpected '<'.

**Comment by erciccione** [comment]
There were some unexpected conflict. lrelease should show now errors now.

**Review by selsta — APPROVED** [review]

**Pull request merged**
