### PR TITLE
Settings: fix page height

### LINKED ISSUE #2471: Unnecessary scroll bar in many pages
Many pages (see Settings) are displaying an unnecessary scroll bar when the content is being completely displayed in the window. 

This seems to happen because the scroll bar is always enabled, unless the window height is at least 
~970 px.

### PR DESCRIPTION
**Pull request by tobtoht**
closes #2471

No more unnecessary scrolling on the settings page.

### CODE REVIEW

**Comment by selsta** [comment]
Nice! Can you increase the bottom margin a bit so that it is like on other pages?

**Comment by rating89us** [comment]
Fixes problem 1 of #2471?

**Comment by tobtoht** [comment]
@selsta Done
@rating89us Yes

**Comment by rating89us** [comment]
Please add "closes #2471" to your first comment.
Thanks

**Pull request merged**
