### PR TITLE
cmake: set current monero-gui version

### PR DESCRIPTION
**Pull request by selsta**
Useful for macOS bundle.

### CODE REVIEW

**Comment by xiphon** [comment]
Don't like hardcoded version approach. Should be set automatically. Will implement this in a while.

**Comment by selsta** [comment]
Would setting automatically also work in environments without git, e.g. when downloading the source code manually?

**Comment by xiphon** [comment]
> Would setting automatically also work in environments without git, e.g. when downloading the source code manually?

Typically source code archive filename contains version suffix. Thinking about obtaining version info from the directory name in that case.

**Comment by selsta** [comment]
Good point.

**Pull request merged**
