### PR TITLE
Adding translations from Weblate

### PR DESCRIPTION
**Pull request by Monero-Weblate**
* Spanish

    * Miguel Medina
    * jaime diaz

* Esperanto

    * Dynse Clyde Sacote
    * Robbie Monero
    * Gilberto F da Silva

* Arabic

    * Malek Atwiz

* Afrikaans

    * nanostos

* Polish

    * ambercookie
    * Patix0331
    * Paul Janowitz

* Icelandic

    * Trendyne

* Indonesian

    * siptruk
    * tuknag

* German

    * Marta Kozera
    * Paul Janowitz

### CODE REVIEW

**Comment by netrik182** [comment]
Please don't merge this it. I downloaded an artifact from CI and some languages (Afrikaans for example) are not showing up.

How can I debug it?

**Comment by selsta** [comment]
Check with the latest release first to see if it shows up correctly.

**Comment by netrik182** [comment]
Confirmed that Afrikaans is not showing on monero-gui-v0.17.3.1-release

**Comment by selsta** [comment]
Ok, can you find the first release it's broken?

**Comment by netrik182** [comment]
> Ok, can you find the first release it's broken?

yeah, looking for it.

**Comment by selsta** [comment]
Also what percentage is Afrikaans fully translated on weblate?

**Comment by netrik182** [comment]
> Also what percentage is Afrikaans fully translated on weblate?

It's 100% translated. First contributions were made on May/21 and last ones (completed) on Aug/21.

Fist commit to include it was this one https://github.com/monero-project/monero-gui/commits/49cce4de9abf0b6406dee46657f7f9c1b860d866/translations/monero-core_af.ts

**Comment by netrik182** [comment]
Looks like more languages are missing. We have 45 on Weblate and 35 in GUI. I will share a summary later.

**Review by selsta — COMMENTED** [review]
As we said on IRC this will need some work before we can merge it, the new languages have to be activated in `lang/languages.xml`. If you add new icons you also have to add them to `qml.qrc`.

**Comment by netrik182** [comment]
I just tested the latest CI build (docker-linux-static) and it looks good now. The five languages added are showing the left panel and strings were properly loaded in GUI.

**Comment by netrik182** [comment]
> Looks like more languages are missing. We have 45 on Weblate and 35 in GUI. I will share a summary later.

Languages added: Afrikaans, Greek, Tamil, Vietnamese and Icelandic

**Review by selsta — APPROVED** [review]
Thanks :)

**Pull request merged**
