### PR TITLE
main: add `_` to end of ttf names of roboto fonts

### LINKED ISSUE #2766: strange font bug
package from arch community repo

this is how it locks:
https://imgur.com/FUgtrBu.png

## ~/.bitmonero/monero-wallet-gui.log

`2020-02-05 08:12:07.988	    7f2f1c859ac0	WARNING	wallet.wallet2	src/mnemonics/language_base.h:198	Español word 'red' is shorter than its prefix length, 4
2020-02-05 08:12:07.988	    7f2f1c859ac0	WARNING	wallet.wallet2	src/mnemonics/language_base.h:198	Español word 'res' is shorter than its prefix length, 4
2020-02-05 08:12:07.988	    7f2f1c859ac0	WARNING	wallet.wallet2	src/mnemonics/language_base.h:198	Español word 'rey' is shorter than its prefix length, 4
2020-02-05 08:13:52.667	    7f2f1c859ac0	WARNING	frontend	src/wallet/api/wallet.cpp:410	qrc:/wizard/WizardOpenWallet1.qml:48: TypeError: Cannot call method 'rowCount' of null
2020-02-05 08:13:52.667	    7f2f1c859ac0	WARNING	frontend	src/wallet/api/wallet.cpp:410	qrc:/wizard/WizardOpenWallet1.qml:72: TypeError: Cannot call method 'rowCount' of null
2020-02-05 08:13:58.902	    7f0d73862ac0	INFO	logging	contrib/epee/src/mlog.cpp:273	New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO
2020-02-05 08:13:58.902	    7f0d73862ac0	WARNING	frontend	src/wallet/api/wallet.cpp:410	app startd (log: /home/suspect/.bitmonero/monero-wallet-gui.log)
2020-02-05 08:13:58.903	    7f0d73862ac0	WARNING	frontend	src/wallet/api/wallet.cpp:410	Qt:5.14.1 GUI:- | screen: 1366x768 - dpi: 96 - ratio:0.885438
2020-02-05 08:14:00.122	    7f0d2e544700	WARNING	frontend	src/wallet/api/wallet.cpp:410	Warning: distance-field glyph is not available with index 1831
2020-02-05 08:14:56.876	    7f0d2e544700	WARNING	frontend	src/wallet/api/wallet.cpp:410	Warning: distance-field glyph is not available with index 1831
`

##Console log
`2020-02-05 08:13:58.902	W app startd (log: /home/suspect/.bitmonero/monero-wallet-gui.log)
2020-02-05 08:13:58.903	W Qt:5.14.1 GUI:- | screen: 1366x768 - dpi: 96 - ratio:0.885438
2020-02-05 08:14:00.122	W Warning: distance-field glyph is not available with index 1831
2020-02-05 08:14:56.877	W Warning: distance-field glyph is not available with index 1831
`

### PR DESCRIPTION
**Pull request by maltejur**
This fixes #2766 by changing the ttf name of Roboto Regular from `Roboto-Regular` to `Roboto-Regular_` with FontForge. This way, if the default system font is Roboto Regular, the `FontLoader` won't load the system font instead of the provideded one, which _apparently_ leads to issues.

image

This doesn't seem like a clean solution to me, but it does the job and I have no idea what else could solve the issue.

### CODE REVIEW

**Comment by selsta** [comment]
https://github.com/monero-project/monero-gui/blob/master/qml.qrc#L129
https://github.com/monero-project/monero-gui/blob/master/components/Style.qml#L10

have to be changed too. At this point it make sense to add a `_` to all custom fonts to avoid it clashing with system fonts.

**Comment by maltejur** [comment]
> have to be changed too

The filename stays the same, what I changed is the name of the font inside the ttf file.

> At this point it make sense to add a _ to all custom fonts to avoid it clashing with system fonts

Yeah probably a good idea. I'll also add that.

**Comment by selsta** [comment]
> The filename stays the same, what I changed is the name of the font inside the ttf file.

Sorry, didn't look properly at the diff :)

**Comment by selsta** [comment]
@rating89us Can you test this on Windows / Linux? Works on Mac for me.

**Comment by rating89us** [comment]
It's working on Ubuntu and Windows.

**Review by luigi1111 — APPROVED** [review]

**Pull request merged**
