### PR TITLE
 wizard/device: hide splash screen

### PR DESCRIPTION
**Pull request by selsta**
Else it will look like this in combination with white theme PR.

Screenshot 2019-04-15 at 08 20 05

@ph4r05 Does this look correct? Is it getting hidden in a different place?

### CODE REVIEW

**Comment by ph4r05** [comment]
Hmm I will need a closer look once I am on PC. 

Do you want to disable splash screen in white theme? I mean, splash screen serves a nice purpose, maybe just splash screen redesign for white theme would be better?

**Comment by selsta** [comment]
@ph4r05 I think with this patch it works fine with white theme.

**Comment by ph4r05** [comment]
Aah OK! Sry. I will check it out properly as soon as I am on PC

**Comment by ph4r05** [comment]
@selsta your commit looks ok! Thanks for fixing it! :)

**Comment by selsta** [comment]
@ph4r05 np, thanks for testing. The PR title could have been worded better.

**Pull request merged**
