### PR TITLE
Logger: runtime log config, no logs till a user selects wallet mode

### PR DESCRIPTION
**Pull request by xiphon**
* Should't create/write any log file till wallet mode gets selected If a user starts Monero GUI for the first time,
* Portable mode: writes log file to `monero-storage` folder.

### CODE REVIEW

**Comment by selsta** [comment]
Screenshot 2020-10-08 at 19 26 25

One starts with `monero-storage/` and the other one displays the full path to monero-storage.

**Comment by xiphon** [comment]
> One starts with `monero-storage/` and the other one displays the full path to monero-storage.

Fixed

**Review by selsta — APPROVED** [review]

**Comment by KarboDuck** [comment]
Can the same fix be applied for folder C:\ProgramData\.shared-ringdb ?

**Comment by xiphon** [comment]
> Can the same fix be applied for folder C:\ProgramData.shared-ringdb ?

Not yet. Requires implementing it in Wallet API, most probably won't be included in v0.17.0.2.

**Pull request merged**
