### PR TITLE
Tx confirmation multiple addresses support

### PR DESCRIPTION
**Pull request by xiphon**
Only the second commit is a subject for review.

monero-tx-confirmation-multiple-recipients

### CODE REVIEW

**Comment by rating89us** [comment]
I think we should display somewhere a destinations count. It could be a numbered list on the destination addresses, like this:
1. Monero Address - 0.01 XMR
2. Monero Address - 0.01 XMR
3. John Doe - 0.02 XMR

**Comment by rating89us** [comment]
Destinations address field is using a different font

**Comment by xiphon** [comment]
> I think we should display somewhere a destinations count. It could be a numbered list on the destination addresses, like this:
> 
>     1. Monero Address - 0.01 XMR
> 
>     2. Monero Address - 0.01 XMR
> 
>     3. John Doe - 0.02 XMR

Updated.

> Destinations address field is using a different font

Yep, using Roboto monospace font. That's intended.

**Comment by rating89us** [comment]
I think it is also important to add fiat conversion after each XMR amount in To: field

Example: 1.00 XMR (150 USD)

**Comment by xiphon** [comment]
> 
> 
> I think it is also important to add fiat conversion after each XMR amount in To: field
> 
> Example: 1.00 XMR (150 USD)

Updated

**Comment by xiphon** [comment]
Rebased

**Review by selsta — APPROVED** [review]

**Pull request merged**
