### PR TITLE
fix clunky scrolling behavior on flickables

### PR DESCRIPTION
**Pull request by tobtoht**

### CODE REVIEW

**Comment by selsta** [comment]
I guess `Flickable.DragAndOvershootBounds` is more of a macOS thing. I wouldn’t call it clunky (macOS has it everywhere) but I can understand that it probably is unusual on Linux/Windows. What do you prefer @xiphon?

**Comment by tobtoht** [comment]
Comparison (Tor required):

http://xmrguide42y34onq.onion/static/overshoot.mp4
http://xmrguide42y34onq.onion/static/stop_at_bounds.mp4

**Comment by rating89us** [comment]
I'm not familiar with MacOS, but if it's the default scrolling behavior, we should keep it in MacOS and remove only for Windows and Linux.

**Comment by selsta** [comment]
Yes, most native macOS apps use this rubber band scrolling. We could do:

`boundsBehavior: isMac ? Flickable.DragAndOvershootBounds : Flickable.StopAtBounds`

**Pull request merged**
