### PR TITLE
addressbook: improve readability by truncating long text and allowing…

### PR DESCRIPTION
**Pull request by mmbyday**
… wrapmode on address/description/paymentid fields. Scales nicely with mobile view.

**Before**
bef

**After**
after

### CODE REVIEW

**Comment by selsta** [comment]
Not sure if you want to spend more time on the address book, but here are two things I found:

- The add button gets disabled after adding a new address or after only half clicking it (see GIF).
out
- Currently, short payment IDs are not allowed to get added. I don’t see a reason for this, as we want to get away from long payment IDs.

**Comment by mmbyday** [comment]
I wonder if it's a qt version issue. I'm on Qt 5.9.5 and can't reproduce the same bug. What version are you on @selsta ? Thanks 
s

**Comment by selsta** [comment]
I’m on 5.11.2.

**Comment by selsta** [comment]
I’ve just noticed that I have this issue with all orange buttons, so this is not something to fix inside this PR.

**Comment by mmbyday** [comment]
No problem. Tested it on windows with qt 5.11.1. All good too.

**Pull request merged**
