### PR TITLE
p2pool: Stop p2pool mining on node switch

### PR DESCRIPTION
**Pull request by devhyper**

### CODE REVIEW

**Comment by plowsof** [comment]
without pr:
<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/77655812/210160031-be04de31-afaf-43e4-b8d4-f80e2adf0750.webm

</details>

with:

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/77655812/210160056-40fc56e6-992d-4778-85c5-ffee854d8b13.webm

</details>

**Comment by plowsof** [comment]
After a closer look. The current behaviour when switching a node is that p2pool 'hangs' and stops working. This PR removes confusion for the user, making it obvious that it has been stopped.

some other out of scope issue here to be addressed in another PR : 
- start mining should 'read values inside the flags box' on click (to avoid having to leave / return to the window to flags take effect)

**Review by plowsof — APPROVED** [review]

**Comment by selsta** [comment]
@devhyper please squash

**Comment by devhyper** [comment]
@selsta Done.

**Review by selsta — APPROVED** [review]

**Pull request merged**
