### PR TITLE
main: skip language page when logging out or changing wallets

### PR DESCRIPTION
**Pull request by mmbyday**
before
eee

after
aft

### CODE REVIEW

**Comment by erciccione** [comment]
Is there a specific reason for skipping the language page? How will be possible to switch to another language then?

**Comment by xmrdsc** [comment]
Note that the wizards are currently being redone, fyi in case you work on something that would maybe be replaced next week!

**Comment by xiphon** [comment]
> Is there a specific reason for skipping the language page? 

In most cases is a redundant step harming UX.

> How will be possible to switch to another language then?

Use `prev page` button on the left.

**Comment by xmrdsc** [comment]
Fixed in #1909

+duplicate

**Pull request closed without merging**
