### PR TITLE
Update README.md with  new Ubuntu dependency

### PR DESCRIPTION
**Pull request by 1337tester**
Updated README.md with new dependency for Ubuntu 16.04+:
+ qml-module-qtquick-controls2

as per issue #1242

### CODE REVIEW

**Comment by pazos** [comment]
Please add qml-module-qt-labs-folderlistmodel too, wich isn't included

**Comment by dEBRUYNE-1** [comment]
Please squash commits.

**Comment by 1337tester** [comment]
spend some considerable time trying to figure out how to squash and then push it here -> unsuccessfully

could you:
a) give me a tip?
b) squash it with the merge? GitHub can supposedly do this - https://i.stack.imgur.com/8t1OJ.png
c) I can delete this PR and make a new one with just one new commit

**Comment by skftn** [comment]
Try:
```
git reset HEAD~1
git add README.md
git commit --amend  (save the 'file' as is)
git push origin patch-1 -f
```

**Comment by 1337tester** [comment]
I tried, but unfortunatelly I started the PR from github GUI, dunno how to navigate properly (must learn the git a bit more for this)
-> closing this one
-> follow up in 1258

**Pull request closed without merging**
