### PR TITLE
wizardhome: fix network dropdown

### LINKED ISSUE #2101: Can't select different networks on wizardhome

### PR DESCRIPTION
**Pull request by mmbyday**
Resolves #2101

### CODE REVIEW

**Comment by xmrdsc** [comment]
Cannot reproduce the problem, don't think this fix is needed.

**Comment by mmbyday** [comment]
It's happening on the nightly builds as well.

**Comment by xmrdsc** [comment]
Sorry, I can reproduce. This is since the new `Flickable` for `WizardController`.

https://github.com/monero-project/monero-gui/blob/bd2687c22f5d147e382e1440fd2f999b83f8dcb4/wizard/WizardController.qml#L110

Set this property to `200` :-)

**Comment by mmbyday** [comment]
Nice call. Updated :-)

**Comment by xmrdsc** [comment]
Nice :-)

**Pull request merged**
