### PR TITLE
Receive: hide payment URL in QR code menu

### PR DESCRIPTION
**Pull request by selsta**

### CODE REVIEW

**Comment by xiphon** [comment]
Don't like this change. It forces even advanced users to read the help to find out that the have to use context menu to copy Payment URL.

Should avoid the context menu. It is counter-intuitive.

Would be better to always show QR code, but hide Payment URL and amount field under the "Advanced options" section. 
What are the downsides?

**Comment by selsta** [comment]
@xiphon had the idea because of @dEBRUYNE-1 comment:

https://github.com/monero-project/monero-gui/pull/1793#issuecomment-446507569

**Comment by xiphon** [comment]
> Would be also okay. I just don’t see a reason to have a huge textbox for the payment URL, all you can do with it is copy anyway.

Yep. Would like to implement "Save As" and "Copy Payment URL" buttons then:
receive-buttons

**Comment by selsta** [comment]
These look good, can you PR them? I tried my own design of this page but failed as I don’t know enough about Qt.

**Comment by xiphon** [comment]
Sure, #1836

**Pull request closed without merging**
