### PR TITLE
AddressBook: redesign

### PR DESCRIPTION
**Pull request by selsta**
Basically exactly @GBKS design.

Screenshot 2019-04-05 at 19 51 30

~~Known bugs: If there is no address book entry, the headline wraps into the text below.~~

### CODE REVIEW

**Comment by mmbyday** [comment]
Very nice. I like the changes @selsta 

A few quick observations

- delete an address book entry not yet working
- edit an address book entry creates an additional new entry
- spacing looks a little tight.
spacing

**Comment by selsta** [comment]
@mmbyday Deleting and editing works fine on my system. (macOS)

What Qt version are you using?

**Comment by mmbyday** [comment]
@selsta 5.11.1, which was the last known working QT version on Windows. Tried QT 5.7 on Windows in the past but no such luck.

**Comment by selsta** [comment]
Note that editing uses a hack (deletes the selected entry + adds a new one with edited information) because there is no edit address book API function. The delete function uses only the API and should work without any problems.

**Comment by selsta** [comment]
I can reproduce the issue with entries not getting deleted when using the buildbot build.

**Comment by selsta** [comment]
Editing and deleting is now working.

**Comment by xmrdsc** [comment]
Working great :+1:

**Comment by luigi1111** [comment]
@selsta please rebase.

**Pull request merged**
