### PR TITLE
Fix for frozen Receive page (requires #3576)

### PR DESCRIPTION
**Pull request by stoffu**

### CODE REVIEW

**Comment by keatond** [comment]
Confirming that I have tested this update and having the tracking turned off by default fixed the issue. When selecting the radio button to turn on tracking the lag re-occurs. If I leave the tracking on and go to other tabs the lag continues. If i go back to the receive tab the lag will stop and the tracking button is unchecked again.

**Comment by keatond** [comment]
Will this be implemented on version 0.12.2.0?

**Comment by erciccione** [comment]
@keatond yes

**Comment by keatond** [comment]
thanks! you guys rock!

**Pull request merged**
