### PR TITLE
[WIP] Move cpp files, clean up includes

### PR DESCRIPTION
**Pull request by xmrdsc**
Requires #2258

The top-dir in this repo contains some miscellaneous `.cpp/.h` files. I moved them to into `src/qt/`, as they don't belong in the root (except for `main.cpp/.h`). This cleans up the repository considerably.

In addition, I've modified the includes to be prefixed by `src/qt` for the sake of being explicit where you're including stuff from.

### CODE REVIEW

**Comment by xmrdsc** [comment]
When merging, this one should go last.

**Comment by jonathancross** [comment]
> When merging, this one should go last (after it has been rebased).

Seems this needs a rebase. :-)

**Comment by jonathancross** [comment]
Friendly ping @xmrdsc

**Comment by selsta** [comment]
I think this can be closed. The files are moved out of the top level directory already and not sure if changing the header path is worth the diff.

**Comment by selsta** [comment]
Cpp files moved already, closing.

**Pull request closed without merging**
