### PR TITLE
receive: add "Download QR-Code image" and "Copy Payment URL" buttons

### PR DESCRIPTION
**Pull request by xiphon**
receive-buttons

### CODE REVIEW

**Comment by selsta** [comment]
The only discussion that remains now is what to show by default and what to hide under advanced.

**Comment by xiphon** [comment]
> The only discussion that remains now is what to show by default and what to hide under advanced.

Yep, but should be done in a separate PR

**Comment by xiphon** [comment]
> Did you also self design these? @2x would be super nice :)

Nope, these icons are from https://useiconic.com/open `data-transfer-download` and `external-link`

**Comment by xiphon** [comment]
To be merged after #1793

**Comment by selsta** [comment]
@xiphon can you rebase this?

**Comment by xiphon** [comment]
Updated
receive-buttons

**Pull request merged**
