### PR TITLE
js: minimize frameless window when clicking on taskbar icon

### LINKED ISSUE #3653: [Windows] GUI Does Not Minimize On Taskbar Icon Click
To reproduce, make sure the GUI is in the foreground and that custom decorations are used.

Next click the Monero GUI icon in the taskbar.
Expected result is for the GUI to minimize to taskbar.
Actual result is no result (as if the program is trying to become the foreground application it already is).

I also noticed that when the minimize icon is clicked, the window just disappears instead of the minimizing to taskbar animation one would expect.

### PR DESCRIPTION
**Pull request by selsta**
Fixes #3653

### CODE REVIEW

**Comment by selsta** [comment]
@elibroftw can you check if this works on Windows? https://github.com/monero-project/monero-gui/suites/6326753598/artifacts/227492115

**Comment by elibroftw** [comment]
Nope

**Comment by elibroftw** [comment]
As in it doesn't work

**Comment by selsta** [comment]
@elibroftw patch was incomplete, next try: https://github.com/monero-project/monero-gui/suites/6337125518/artifacts/228213660

**Comment by elibroftw** [comment]
works.

**Comment by selsta** [comment]
ok, please approve it and I'll add it to the merge queue

**Review by elibroftw — APPROVED** [review]

**Pull request merged**
