### PR TITLE
Transfer: add Address Book inline button in Address field

### PR DESCRIPTION
**Pull request by rating89us**
Changes:
- Remove "(Address Book)" link from address field label
- Add address book inline button with icon + adjust right margin of address field
- Add second inline button (scan QR code button)
- Change color of scan QR code button

Address book inline button as single inline button:
inlineaddressbutton3

With scan QR code button enabled:
inlinewithqrcode

### CODE REVIEW

**Comment by xiphon** [comment]
And another not mentioned change is removing "Scan QR code" inline button

**Comment by rating89us** [comment]
I thought the scan QR code button was disabled so I commented those lines. Do you think I should implement this address book button as a 2nd inline button and keep the scan QR code button?

**Comment by selsta** [comment]
You can still compile with QR scanner enabled.

**Comment by rating89us** [comment]
Updated

**Comment by rating89us** [comment]
In my opinion scan QR code button should be always visible (when enabled). Currently it is hidden when the address field isn't empty. What do you think?

**Comment by xiphon** [comment]
> In my opinion scan QR code button should be always visible (when enabled).

Yep, agree

**Comment by selsta** [comment]
What is the opinion on adding a `Scan QR code` menu item instead of a second inline button?

Screenshot 2020-04-16 at 03 17 24

**Comment by xiphon** [comment]
Think nobody will ever know the feature exists then.

**Pull request merged**
