### PR TITLE
RemoteNodeList, RemoteNodeDialog: different remote node for each network type; implement labels

### LINKED ISSUE #3819: [Feature Request] Better Remote Node Experience
1. Users should be able to assign labels or nicknames to remote nodes
image
I would like more than just a port number to differentiate the node network.
2. Remote nodes should be saved for each type of wallet. 
Suppose I have remote nodes X (stagenet), Y (stagenet), and Z (mainnet). I'm currently in a stagenet wallet connected to X. I exit and open mainnet wallet and switch the remote node to Z. I then open up a stagenet wallet. A good UX would connect the stagenet wallet to the remote node X, but currently the behaviour is that it connects to remote node Z. This results in wallet-node mismatch.

### PR DESCRIPTION
**Pull request by rating89us**
closes #3819

### CODE REVIEW

**Comment by jonathancross** [comment]
Nice PR!
Needs a rebase.

**Comment by plowsof** [comment]
This is a great feature :+1:  would solve alot of my personal headaches

**Comment by jonathancross** [comment]
@rating89us ?

**Comment by elibroftw** [comment]
I did the rebase myself https://github.com/monero-project/monero-gui/pull/4163

**Comment by selsta** [comment]
Continuing in #4163

**Pull request closed without merging**
