### PR TITLE
Tiny spell update in dutch translation

### PR DESCRIPTION
**Pull request by fridzema**
Dutch explanation:
https://www.beterspellen.nl/website/index.php?pag=106

has to do with noun and adjective words.

### CODE REVIEW

**Comment by dEBRUYNE-1** [comment]
Please use a more descriptive title.

**Comment by skftn** [comment]
Approved.

**Comment by skftn** [comment]
Could you do a `git commit -m "Fixing Dutch translation spelling mistake" --amend && git push origin patch-1 -f` ?

Voor de rest, bedankt ;)

**Comment by fridzema** [comment]
Cant get it to work i close this one and make a new one.

**Comment by erciccione** [comment]
@fridzema if you need help/support you'll find it on `#monero-translations` (irc-freenode, slack, riot/matrix)

**Comment by fridzema** [comment]
@erciccione thanks for your reply!
I have managed to get it done with a fresh pull request, next time i do it the preferred way.

**Pull request closed without merging**
