### PR TITLE
Docker android: upgrade build tools and dependencies

### PR DESCRIPTION
**Pull request by Malinero**
jftr, latest stable libgpg-error is 1.42 (not 1.41 in this PR) but it fails to build.

### CODE REVIEW

**Comment by selsta** [comment]
5.15.6 is the latest Qt version, could you update it?

**Comment by Malinero** [comment]
> 5.15.6 is the latest open source Qt version, could you update it?

doesn't work, I guess it requires a newer NDK, but they cause other problems

```
src/org/qtproject/qt5/android/ExtractStyle.java:418: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q)
                                                           ^
  symbol:   variable Q
  location: class VERSION_CODES
src/org/qtproject/qt5/android/ExtractStyle.java:421: error: cannot find symbol
                numStates = stateList.getStateCount();
                                     ^
  symbol:   method getStateCount()
  location: variable stateList of type StateListDrawable
```

**Comment by Malinero** [comment]
Updated Qt to 5.15.6 (required to also update API level)

**Review by selsta — APPROVED** [review]

**Review by 01SMD — COMMENTED** [review]
.

**Review by 01SMD — COMMENTED** [review]
.

**Review by 01SMD — COMMENTED** [review]
.

**Review by 01SMD — COMMENTED** [review]
.

**Pull request merged**
