### PR TITLE
Docker: update Qt 5.15.2 -> 5.15.3

### PR DESCRIPTION
**Pull request by selsta**

### CODE REVIEW

**Comment by selsta** [comment]
@elibroftw Can you download the Windows build and check if you still have issues closing?

You can click on `Details` next to `ci/gh-actions/gui / build-windows` to find the download or you can use this link:

https://github.com/monero-project/monero-gui/suites/5802699631/artifacts/194048449

I'm quite sure it won't be fixed but it would still be good to have it confirmed.

**Comment by elibroftw** [comment]
I still face the same issue. I thought it was fixed, but the issues strongly depends on length of time the GUI is running for.

**Comment by selsta** [comment]
Welp, as expected. Thanks for testing.

**Review by mj-xmr — APPROVED** [review]
Relevant mailing list's message:

https://lists.qt-project.org/pipermail/development/2022-March/042262.html

**Pull request merged**
