### PR TITLE
macOS: enable fullscreen support

### PR DESCRIPTION
**Pull request by selsta**
Requires custom decorations turned off.

Screenshot 2019-04-26 at 01 32 43

### CODE REVIEW

**Comment by xmrdsc** [comment]
Some `show()` thingies in your commit. As for WindowHint, this does not impact custom decorations?

**Comment by selsta** [comment]
Custom decorations have their own flags. This removes show() because show() changes the window size back to default every time it gets called.

**Comment by luigi1111** [comment]
@selsta please rebase.

**Comment by selsta** [comment]
rebased

**Pull request merged**
