### PR TITLE
Bulgarian language

### PR DESCRIPTION
**Pull request by whotheff**
te

### CODE REVIEW

**Comment by whotheff** [comment]
Hi, please write me if something else should be done to compelte Bulgarian translation addition to GUI

**Comment by erciccione** [comment]
@whotheff Could yo include commits from #1627 and #1628 into this PR and close those? There is really no point in having 3 PRs open for this, and it also makes reviews much harder

**Comment by whotheff** [comment]
> @whotheff Could yo include commits from #1627 and #1628 into this PR and close those? There is really no point in having 3 PRs open for this, and it also makes reviews much harder

Sorry, I have no idea how to do that. If you guide me I can try.

**Comment by skftn** [comment]
Fixed in #1637

**Pull request closed without merging**
