### PR TITLE
main: keep wizard in background when switching wallets

### LINKED ISSUE #1159: Open a wallet from file displays Settings page in the background
Open a wallet from file -> It will display the settings page of the GUI in the background.

### PR DESCRIPTION
**Pull request by mmbyday**
resolves #1159

### CODE REVIEW

**Comment by xmrdsc** [comment]
Tested, reviewed.

**Comment by xmrdsc** [comment]
Approved too quickly.

I have 2 suggestions here:



For every change, you must think to yourself, does this look good? I don't think this does. I suggest to create a new blank panel @ middlepanel stackview and switch to that. It will look better, plus you'll have a titlebar.

**Comment by xmrdsc** [comment]
Could you join IRC? `#monero-gui` on freenode :-)

**Comment by erciccione** [comment]
Or riot/matrix or MatterMost :)

**Comment by xmrdsc** [comment]
Fixed in #1909

+invalid

**Pull request closed without merging**
