### PR TITLE
Transfer: hide PaymentId and Description by default

### PR DESCRIPTION
**Pull request by xiphon**
Requires #1853 #1854 

Feedback and comments on proposed change are welcome.

transfer-hide-payment-id

### CODE REVIEW

**Comment by rbrunner7** [comment]
Looks reasonable to me. A good compromise between slowly phasing out payment ids but still supporting them for the time being.

**Comment by selsta** [comment]
I’m like this feature but I’m still unhappy abhout how Payment IDs is now not aligned with the other labels.

Maybe it’s possible to add the + to the left of the Payment ID label and align it like it was before.

**Comment by SamsungGalaxyPlayer** [comment]
We go even further and say (optional, will be deprecated March/April 2019). See Monero [issue 3772](https://github.com/monero-project/monero/issues/3772).

Of course, this is contingent on agreeing to remove them in the next upgrade.

**Comment by xiphon** [comment]
Updated

**Comment by xiphon** [comment]
Updated to hide Description field too.

**Comment by dEBRUYNE-1** [comment]
I'd remove the `will be deprecated March/April 2019` part for now, as there's no consensus yet on when the long, unencrypted payment ID will be deprecated.

**Comment by xiphon** [comment]
> I'd remove the `will be deprecated March/April 2019` part for now, as there's no consensus yet on when the long, unencrypted payment ID will be deprecated.

Yep. Updated the PR.

**Pull request merged**
