### PR TITLE
Slovak translation

### PR DESCRIPTION
**Pull request by fero-sk**
First version.

### CODE REVIEW

**Comment by KanoczTomas** [comment]
Hello, added a review of the translation see #983. Nice job @fero-sk!

**Comment by erciccione** [comment]
@fero-sk Another translation was merged and now this one has some conflicts. Can you solve them pls?

**Comment by fero-sk** [comment]
Done.

**Comment by erciccione** [comment]
nope :) you need to remove the merge commit first and then rebase

**Pull request merged**
