### PR TITLE
StandardDropdown: fix variable name (> Qt 5.7)

### PR DESCRIPTION
**Pull request by selsta**
Qt 5.12

Newer Qt versions don't like the name "column"

### CODE REVIEW

**Comment by xmrdsc** [comment]
Shadowing built-in keyword or?

**Comment by selsta** [comment]
> Shadowing built-in keyword or?

Not sure what that means.

Before:
before
After:
after

**Comment by mmbyday** [comment]
Shadowing as in reserved word. Overlaps with an existing thing. In either case, this looks good to me :P Thanks

**Comment by xmrdsc** [comment]
Works on 5.7.

**Pull request merged**
