### PR TITLE
ContextMenu: implement 'paste' context menu for all text fields

### LINKED ISSUE #2359: The "Receive" tab format gives an address that doesn't fit the "Spend" tab format
image

The button here gives an output that looks like this: `monero:49dpgSbHdA6auSv2gMPEsfj3uXVqqon4LEGWpuhdfXJsULVLKjFXkFQhpywAU8WddGbsN2ZDDpiVb8byZH6FfgL2R7ZwKZE`

If you paste this in the send tab, it looks like this:

image

And it's not a valid address.

### PR DESCRIPTION
**Pull request by xiphon**
Fixes #2359
Partially addresses #2405

context-menu-paste

### CODE REVIEW

**Comment by selsta** [comment]
Can you disable the paste button on inputs that are read only? e.g. adding

```
diff --git a/components/InputMulti.qml b/components/InputMulti.qml
index 8fccb6a..c64acfe 100644
--- a/components/InputMulti.qml
+++ b/components/InputMulti.qml
@@ -70,6 +70,7 @@ TextArea {
     }
 
     MoneroComponents.ContextMenu {
+        visible: !parent.readOnly
         onPaste: {
             textArea.clear();
             textArea.paste();
```

to every input. Better solution would be to have a disable paste property as other context menu items could still exist.

**Comment by xiphon** [comment]
> e.g. adding ... to every input. 

No

> Better solution would be to have a disable paste property

No

> Can you disable the paste button on inputs that are read only?

Yes. Updated

**Comment by xiphon** [comment]
Updated. Now you can paste a seed during wallet restore.

PS: Will update remaining `TextArea`s later (in a separate PR). There's no hurry cause all of them are readOnly, so you can't use `paste` anyway.

**Comment by Realchacal** [comment]
NICE!!!!!!!!!

Any chance to get...

- rounded edges?
- light text color? (which doesn't make the button look disabled)
- shadow? (which makes it look like an element with depth that can be clicked)
- a larger button? (which reminds of a [classical context menu](https://ourcodeworld.com/public-media/articles/articleocw-5c9a7439d33aa.png))

image

**Comment by xiphon** [comment]
> Any chance to get...
> 
>     * rounded edges?

the edges are already rounded

**Comment by Realchacal** [comment]
> the edges are already rounded

Oh you're right. Didn't see.

image

**Pull request merged**
