### PR TITLE
Update Swedish translation with changes in PR #1609

### PR DESCRIPTION
**Pull request by snaggen**
I took the liberty to incorporate the changes suggested to the swedish translation in the review comments to PR #1609

### CODE REVIEW

**Comment by snaggen** [comment]
ping @erciccione

**Comment by erciccione** [comment]
@snaggen Is this PR based on #1609 ?

**Comment by snaggen** [comment]
I pulled the latest master, and just added the things from #1609 .

**Comment by erciccione** [comment]
That won't make it. You need to use 1609's branch as a base and then add your suggested strings, or all the new strings introduced by 1609 will get reverted

**Comment by snaggen** [comment]
Didn't you merge #1609 to master?

**Comment by erciccione** [comment]
yes, sorry... I need some rest.
Will review this in a bit, meanwhile @ordtrogen @freminik Could you review this?

**Comment by snaggen** [comment]
I have latest master with this commit in my history, so it should be fine


commit cd87af1415e2e29c38677a185e580247cc9a886c
Merge: 6693fc7 703e499
Author: luigi1111 <luigi1111w@gmail.com>
Date:   Tue Oct 9 17:32:30 2018 -0500

    Merge pull request #1621
    
    703e499 Update monero-core_sv.ts (freminik)

**Pull request merged**
