### PR TITLE
Compact margins for transfer optionals

### PR DESCRIPTION
**Pull request by xmrdsc**
Compact margins for the optional buttons.

@mmbyday I think this looks better. What do you think?

### CODE REVIEW

**Comment by selsta** [comment]
ou2
Is this working as intended?

**Comment by xmrdsc** [comment]
Yes. You dont like that margin change I take it? Personally I dont mind.

**Comment by selsta** [comment]
Yep, I don’t really like it, I think the current margins are fine.

**Comment by mmbyday** [comment]
@xmrdsc nice in thought. although at first impression, before looks more balanced. bigger picture, i think this page can be improved with a layout redesign. amount, destination, send button are primary; everything else gets de-prioritized / tucked away.

**Pull request closed without merging**
