### PR TITLE
TxConfirmationDialog: warn high fees

### PR DESCRIPTION
**Pull request by selsta**
Screenshot 2022-04-27 at 17 42 26

### CODE REVIEW

**Review by reemuru — COMMENTED** [review]
LGTM, compile tested and triggered high fee display

pr3897

**Review by reemuru — APPROVED** [review]

**Review by jeffro256 — APPROVED** [review]

**Comment by jeffro256** [comment]
This shouldn't be the only long-term solution, but it's a nice quick fix for now!

**Comment by reemuru** [comment]
> This shouldn't be the only long-term solution, but it's a nice quick fix for now!

@jeffro256 
agree, i can create and issue: 

`"Update Magic for high fee"`   ?

**Comment by selsta** [comment]
The only long term solution will be to remove the remote node scanner from simple mode and use hardcoded trusted nodes.

**Comment by jeffro256** [comment]
@selsta Or have nodes provide some kind of blockchain proof that their recommended fee is reasonable

**Comment by SamsungGalaxyPlayer** [comment]
Apologies for being out of the loop here, but some sanity checks:

1. Does the current code show this warning if fees are > 0.01 XMR?
2. Does the current code check if the fee follows an appropriate multiplier set in the wallet defaults? We don't want wallets tricked to send unique fee values either.

@selsta

**Comment by selsta** [comment]
> Does the current code show this warning if fees are > 0.01 XMR?

Yes, I changed it for the screenshot to demonstrate it. I'm open for different values.

> Does the current code check if the fee follows an appropriate multiplier set in the wallet defaults? We don't want wallets tricked to send unique fee values either.

As far as I understand it the wallet calculates the fee with data from the daemon. If the daemon tricks you like in this case I'm not sure what you want to do on wallet side.

**Comment by plxkax** [comment]
> The only long term solution will be to remove the remote node scanner from simple mode and use hardcoded trusted community nodes.

It would be good to offer the choice between remote node or having the trusted community node. You don't want to make it feel like it's being forced, user should have the option to decide.

**Comment by selsta** [comment]
You can either use simple mode, which automatically will connect you to a community node or you can use advanced mode which allows you to set your own remote node.

**Comment by plxkax** [comment]
> 

Would there be any security compromises with automatically having all simple mode users onto community node only?

**Comment by selsta** [comment]
Security compromises compared to now? No. Simple mode already connects to a random remote node.

**Comment by plxkax** [comment]
To confirm, **Simple mode currently connects to a random remote node automatically** but with this change **Simple mode will connect to a community trusted node automatically** with no security compromises compared to now?

**Comment by plxkax** [comment]
Do we have an any idea as to how big the community trusted node list will be?

**Comment by selsta** [comment]
Correct.

**Comment by selsta** [comment]
> Do we have an any idea as to how big the community trusted node list will be?

Around 10 maybe? Don't know yet.

**Comment by nixt7** [comment]
It's GUI discussed here. But what about wallet RPC? It needs protection from high fees too.

**Comment by selsta** [comment]
The GUI simple mode currently connects you to a random remote node that's why it was important to add the warning here quickly. The RPC wallet doesn't have such a feature so it is way more unlikely that you run into the high fee issue in the first place, unless you manually connect to a malicious remote node.

**Comment by fugbixer** [comment]
maybe adding a won't proceed when the xmr fee is above a certain unreasonable amount like 0.5+ would be nice to make it safe. even when i don't like of adding a limit.

It could need something that's complete obvious for non technical users to see something is wrong and they should not continue.

**Pull request merged**
